### ISSUE TITLE
Author receives notification emails, commenter does not

### ISSUE THREAD

**Issue by nicbou** [verbb/comments#100]
### Description

I enabled author and reply notifications. Author notifications work, but reply notifications don't. No email is sent.

### Steps to reproduce

1. Enable reply notification
2. Leave reply

### Additional info

- Plugin version: 0.4.9
- Craft version: 2.7.2

**Comment by nicbou** [comment]
I found the issue: it fails [here](https://github.com/verbb/comments/blob/craft-2/comments/services/CommentsService.php#L450) because both values are null. I simply removed that line. I also noticed that [this block](https://github.com/verbb/comments/blob/craft-2/comments/services/CommentsService.php#L136-L144) will send notifications before the comments are approved. Depending on your desired behaviour, this could be an issue.

**Comment by engram-design** [comment]
I believe this was semi-desired behaviour where only user accounts were allowed to have notifications. For instance, if your settings were to allow anonymous users, these guests wouldn't be notified.

This should be fixed in [0.5.1](https://github.com/verbb/comments/releases/tag/0.5.1).
