### ISSUE TITLE
Multisite issue when viewing/editing comments

### ISSUE THREAD

**Issue by colinmeinke** [verbb/comments#104]
### Description

Error thrown when navigating to `/admin/comments/edit/<comment-id>` and the comment is associated with a site that is not the site your admin user's is viewing.

### Steps to reproduce

1. Create a comment associated to a siteId that is not your admin user's default site ID.
2. Go to `/admin/comments`.
3. Select the entry that has the comment you just created.
3. Switch the site to the one associate with the comment.
5. Click to edit the comment.

It will throw an error because the comment is not found.

This is because no site ID has been passed to `getCommentById` so it uses your admin user's default site ID, which is not the correct site for the comment.

I believe Craft manage to get around this with channels by adding the site handle to the end of the edit route, so they can then retrieve the site ID. So instead of `/admin/comments/edit/<comment-id>` you probably want to do `/admin/comments/edit/<comment-id>/<site-handle>`. Then inside `actionEditTemplate` you can get site ID from the site handle, and pass it as the second argument to `getCommentById`.

### Additional info

- Plugin version: 1.0.3
- Craft version: 3.x

**Comment by colinmeinke** [comment]
```php
private function _registerCpRoutes()
{
    Event::on(UrlManager::class, UrlManager::EVENT_REGISTER_CP_URL_RULES, function(RegisterUrlRulesEvent $event) {
        $event->rules = array_merge($event->rules, [
            'comments/edit/<commentId:\d+>/<siteHandle>' => 'comments/comments/edit-template',
            'comments/settings' => 'comments/base/settings',
        ]);
    });
}
```

```php
public function actionEditTemplate($commentId, $siteHandle)
{
    $site = Craft::$app->getSites()->getSiteByHandle($siteHandle);
    $comment = Comments::$plugin->getComments()->getCommentById($commentId, $site->id);

    return $this->renderTemplate('comments/comments/_edit', [
        'comment' => $comment,
    ]);
}
```

`$siteId` also needs to be passed to `getElementById`:

```php
public function getCommentById(int $id, $siteId = null)
{
    return Craft::$app->getElements()->getElementById($id, Comment::class, $siteId);
}
```

**Comment by engram-design** [comment]
Updated in [1.0.4](https://github.com/verbb/comments/releases/tag/1.0.4) thanks for your PR.
