### ISSUE TITLE
Feature request; language files for error messages

### ISSUE THREAD

**Issue by arifje** [verbb/comments#106]
Looks like all messages are hard coded at the moment; would be nice if we can create custom language files.

**Comment by engram-design** [comment]
Not sure what you mean by "all messages are hard coded"? Everything in the plugin hooks into the translations functionality that Craft provides - even the dynamic messages generated in JS hook into the translations. Can you let me know what you might be trying to change, or if something isn't working correctly?

**Comment by arifje** [comment]
Sorry, I was too quick with my conclusion, I see that I can create the translation files myself and add the variables myself!
