### ISSUE TITLE
Can't use emojis in comments

### ISSUE THREAD

**Issue by arifje** [verbb/comments#109]
When you copy paste emojis into your comments, the server returns a 500 error when submitting it.

<img width="929" alt="screenshot 2019-01-09 at 20 04 20" src="https://user-images.githubusercontent.com/1286410/50922074-d463f700-1449-11e9-9e35-12adfa2535b3.png">

Copy pasted the emojis from: https://nl.piliapp.com/facebook-symbols/

Craft CMS 3.0.36
Comments 1.0.4

**Comment by engram-design** [comment]
Added in [1.0.5](https://github.com/verbb/comments/releases/tag/1.0.5).
