### ISSUE TITLE
General error on upvote on local server

### ISSUE THREAD

**Issue by mblode** [verbb/comments#110]
### Description

```
SQLSTATE[HY000]: General error: 1364 Field 'commentDate' doesn't have a default value The SQL being executed was: INSERT INTO `comments_votes` (`commentId`, `userId`, `upvote`, `downvote`, `dateCreated`, `uid`, `dateUpdated`) VALUES (172, 1, 1, NULL, '2019-01-21 04:52:09', '02f844e7-8fc4-4f63-b398-80725d38e926', '2019-01-21 04:52:09')
```

### Steps to reproduce

1. Install the plugin via composer and enable in Craft
2. Use `{{ craft.comments.render(entry.id) }}` to generate the form on Front-end
2. Post comment as an admin user
3. Approve comment in the back-end
4. With the same account, try to upvote the comment

### Additional info

- Plugin version: 1.0.4
- Craft version: ^3.0

**Comment by engram-design** [comment]
Fixed in [1.0.5](https://github.com/verbb/comments/releases/tag/1.0.5).
