### ISSUE TITLE
Can't populate comments field when importing via FeedMe

### ISSUE THREAD

**Issue by evanbartlett** [verbb/comments#115]
### Description
Can't populate comments field when importing via FeedMe. Using the same data structure I've had no problem mapping over all of the other data via XML, however with this comments plugin it populates every possible field, except the actual comments. In my logs for FeedMe I see no errors, but when viewing the comments, every single comment is empty.

### Steps to reproduce

1. Create a new feed within FeedMe and select "Comment" as the entry type
2. Enter url to feed (in my case it was local xml)
3. Map data accordingly
3. Run feed

### Additional info

- Plugin version: 1.1.1
- Craft version: 3.1.3

**Comment by engram-design** [comment]
Are you on the latest version of Feed Me? Can you also try with the latest version of Comments as well? [1.1.2](https://github.com/verbb/comments/releases/tag/1.1.2)

**Comment by evanbartlett** [comment]
@engram-design Thank you! It was indeed an update issue. After updating everything, I'm now seeing the comments being populated.
