### ISSUE TITLE
Unknown column when accessing comments

### ISSUE THREAD

**Issue by ilicmarko** [verbb/comments#119]
### Description
When I install comments and open the tab in admin panel I get this error:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'elements.dateDeleted' in 'field list'
```

Full error:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'elements.dateDeleted' in 'field list'
The SQL being executed was: SELECT `elements`.`id`, `elements`.`type`, `comments`.`ownerId`, `content`.`title`, `elements`.`dateDeleted`
FROM `craft_elements` `elements`
INNER JOIN `craft_content` `content` ON `content`.`elementId` = `elements`.`id`
INNER JOIN `craft_comments_comments` `comments` ON `comments`.`ownerId` = `elements`.`id`
WHERE `elements`.`dateDeleted` IS NULL
GROUP BY `ownerId`
LIMIT 25
```

As far as I know this used to be a migration issue for craft 3.0 to 3.1 but in the requirements it says that the plugin works `3.x`

### Steps to reproduce

1. Install plugin
2. Open `/admin/comments`

### Additional info

- Plugin version: `1.1.3` 
- PHP version: `7.2.14`
- Database driver & version: `MySQL 5.7.24`
- Craft version: `Craft Solo 3.0.41`

**Please note that settings area works `/admin/comments/settings`.**

**Comment by ilicmarko** [comment]
The problem was introduced with this commit: https://github.com/verbb/comments/commit/735ccb513f9976bea56976b9bdca293e3c41ded6

**Affected version:** `1.1.3`

This is because craft `<3.1` doesn't have soft delete for elements. Therefore there isn't a `dateDeleted` column.

**Comment by engram-design** [comment]
Should be fixed in the latest craft-3 code, which you can install via `composer require verbb/comments:dev-craft-3` before we push a new release.

**Comment by engram-design** [comment]
Added in [1.1.4](https://github.com/verbb/comments/releases/tag/1.1.4)
