### ISSUE TITLE
FR: Return vote count including nested comments

### ISSUE THREAD

**Issue by ilicmarko** [verbb/comments#120]
### Description
Return complete vote count, because `{{ commentsQuery.all() | length }}` will only return count for the first level.

Facebook and most commenting services include nested comments in the count.

**Comment by engram-design** [comment]
Can you share your code that's fetching the vote count? 

Using `{{ craft.comments.fetch({ ownerId: entry.id }).count() }}` will fetch the total count of **comments** for a particular element, regardless of their nesting level, but there's no straight alternative to get all votes, or flags for a particular entry. Or - is this part of the feature request?

**Comment by ilicmarko** [comment]
Yeah kind of my mistake. I use custom templates and I know you pass `commentsQuery` to the template but didn't look at the code what the query is.
After this I checked and it returns only level 1

```php
$query = Comment::find();
$query->ownerId($elementId);
$query->level('1');
$query->orderBy('commentDate desc');
```
Now with `craft.comments.fetch({ ownerId: element.id })` I would need to change the logic of rendering items.

Another thing I notices with `commnetsQuery` you will have to make a lot of queries. Because I will make a query for each sublevel.

Therefore I will go with `craft.comments.fetch({ ownerId: element.id })`, so I guess no need for vote count.

Edit: To be honest I am not sure how I will render a 1 dimensional array of comments into nested comments but I will try.
