### ISSUE TITLE
ANY_VALUE breaks MariaDB

### ISSUE THREAD

**Issue by abdusco** [verbb/comments#122]
### Description
https://github.com/verbb/comments/commit/b3f1aeae38e4b61fc3a8bb97519dff228d12f2f9 commit [adds `ANY_VALUE`][0] function, which [does not exist on MariaDB][1]. Reverting the commit fixes the issue

### Steps to reproduce

1. Update `verbb/comments` to https://github.com/verbb/comments/commit/b3f1aeae38e4b61fc3a8bb97519dff228d12f2f9
2. View commented entries on the admin panel `/admin/comments`, you get this error:

```
SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION craft.ANY_VALUE does not exist
The SQL being executed was: SELECT `elements`.`id`, `elements`.`type`, `comments`.`ownerId`, ANY_VALUE(content.title) AS title, `elements`.`dateDeleted`
FROM `elements` `elements`
INNER JOIN `content` `content` ON `content`.`elementId` = `elements`.`id`
INNER JOIN `comments_comments` `comments` ON `comments`.`ownerId` = `elements`.`id`
WHERE `elements`.`dateDeleted` IS NULL
GROUP BY `ownerId`
LIMIT 25
Error Info: Array
(
    [0] => 42000
    [1] => 1305
    [2] => FUNCTION craft.ANY_VALUE does not exist
)
```

### Additional info

- Plugin version: https://github.com/verbb/comments/commit/b3f1aeae38e4b61fc3a8bb97519dff228d12f2f9
- Craft version: `Craft CMS 3.1.23`
- MariaDB version: `mysql  Ver 15.1 Distrib 10.3.13-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
`

[0]: https://github.com/abdusco/comments/blob/b3f1aeae38e4b61fc3a8bb97519dff228d12f2f9/src/elements/Comment.php#L124

[1]: https://jira.mariadb.org/browse/MDEV-10426?focusedCommentId=85142&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-85142

**Comment by engram-design** [comment]
Bah - This was done to fix a similar issue with Postgres, looks like we can't please all the DB systems!

Can you run `composer require verbb/comments:dev-craft-3` just to test this fix out?

**Comment by abdusco** [comment]
It works like a charm, thank you :ok_hand:

**Comment by engram-design** [comment]
Added in [1.1.4](https://github.com/verbb/comments/releases/tag/1.1.4)
