### ISSUE TITLE
FR: Clearing form on submit

### ISSUE THREAD

**Issue by ilicmarko** [verbb/comments#123]
### Description
This a really simple but useful feature. I will probably make a PR if you are ok with the idea.

When a comment is submitted with AJAX the form will stay filled in, and if we didn't set flooding protection someone can click and re-submit the same comment, over and over again.

A simple way to prevent this is by clearing the form when the comment is successfully submitted.

**Note that if an error happens the form shouldn't clear as this is bad UX, only on success.**

**Comment by engram-design** [comment]
Totally agree, and thanks for the PR!

Added in [1.1.5](https://github.com/verbb/comments/releases/tag/1.1.5)
