### ISSUE TITLE
Spam check ignoring banned/blacklisted keywords 

### ISSUE THREAD

**Issue by arifje** [verbb/comments#129]
We are receiving a lot of spam comments lately so we started blacklisting/banning all kinds of keywords and domain names. Unfortunately these comments are still being posted, although we've added them to the banned/blacklisted comments.

Screenshots;

![Screenshot 2019-06-11 at 10 04 05](https://user-images.githubusercontent.com/1286410/59254985-85590280-8c31-11e9-993a-8e07db6cadba.jpg)
![Screenshot 2019-06-11 at 10 09 51](https://user-images.githubusercontent.com/1286410/59254992-8a1db680-8c31-11e9-925b-aaab6f4a7ca4.jpg)

Running Craft CMS 3.1.28 and Comments 1.1.6

**Comment by engram-design** [comment]
Looks like there's some sneaky encoding going on there that makes characters look like URLs (and other blacklisted strings), but due to those characters the rules aren't matching.

Fixed in [1.1.8](https://github.com/verbb/comments/releases/tag/1.1.8) by introducing encoding cleaning.
