### ISSUE TITLE
Craft 3.2 allow anonymous 

### ISSUE THREAD

**Issue by Zae** [verbb/comments#133]
### Description
It seems that something is broken with the `$allowAnonymous` system, this might be because of the recent changes in craft 3.2.

It seems that the controller is setup to allow anonymous access to `actionSave`, however, craft is now checking the `$allowAnonymous` system for the key `save` and that is obviously not added to the array. 

This check if done in: craft/vendor/craftcms/cms/src/web/Controller.php:154

Because if this it's not possible to add comments anonymously.

### Steps to reproduce

1. Use verbb/comments with craft 3.2
2. try to add an anomymous comment
3. Get a 503 because of the anonymous check

### Additional info

- Plugin version: 1.1.7.1
- Craft version: 3.2.5.1

**Comment by theskyfloor** [comment]
Does this matter if we have public comments off?

**Comment by engram-design** [comment]
@Zae Yep, a hangover from Craft 2 that did actually work, although technically incorrect. Updating to Craft 3.2 caused this non-issue to become an issue. Fixed in [1.1.8](https://github.com/verbb/comments/releases/tag/1.1.8).

@theskyfloor This shouldn't be an issue for private commenting.
