### ISSUE TITLE
Can't edit comment in CP

### ISSUE THREAD

**Issue by Zae** [verbb/comments#136]
### Description
It's not possible to edit comments in the CP, because the comment is sent in a field called `fields[comment]` but in the CommentsController:62 the field `comment` is fetched from the request, this is obviously wrong and therefor the default (old comment) is used.

### Steps to reproduce

1. Create a comment
2. Edit a comment in the CP
3. Old comment is back.

### Additional info

- Plugin version: 1.1.7.2
- Craft version: 3.2.5.1

**Comment by engram-design** [comment]
Fixed in [1.2.0](https://github.com/verbb/comments/releases/tag/1.2.0).
