### ISSUE TITLE
Anonymous commenting fails completely when CSRF is enabled

### ISSUE THREAD

**Issue by adrienne** [verbb/comments#141]
### Description

In Craft 3.3.x, when CSRF protection is enabled, commenters cannot comment anonymously -- you get a 400 "Unable to verify your data submission" error. Disabling CSRF using the config setting
```
'enableCsrfProtection' => false
````
solves the problem, but is an obvious security issue.

### Steps to reproduce

1. Enable CSRF protection (it's on by default)
2. Try commenting anonymously

### Additional info

- Plugin version: 1.1.10
- Craft version: Craft Pro 3.3.13

**Comment by adrienne** [comment]
Okay, disregard this issue, it was a separate plugin having a conflict. Sorry!

**Comment by engram-design** [comment]
Ah okay, what plugin was it out of interest?

**Comment by adrienne** [comment]
@engram-design - it was the "HTML Cache" plugin, which was caching things badly.
