### ISSUE TITLE
Feature request: able to retrieve comments using GraphQL API

### ISSUE THREAD

**Issue by bzin** [verbb/comments#142]
### Description

Is it possible to have the comments being accessible via the new GraphQL?

Not sure how complex this can be but it could be very interesting and useful to be able to use `Comments` plugin using  Craft in headless mode.

**Comment by engram-design** [comment]
Added in [1.2.0](https://github.com/verbb/comments/releases/tag/1.2.0).

See also the docs page - https://verbb.io/craft-plugins/comments/docs/developers/graphql

**Comment by bzin** [comment]
Awesome!
