### ISSUE TITLE
Settings in project configuration should use UIDs

### ISSUE THREAD

**Issue by gglnx** [verbb/comments#144]
### Description

The plugin configuration saved to `project.yaml` uses IDs (`structureId`, `permissions`) from the database. If deployed into a another environment these IDs not always match.  

### Steps to reproduce

1. Install the plugin in a development environment.
2. Commit project.yaml
3. Deploy into production environment.

### Additional info

- Plugin version: 1.1.10
- Craft version: 3.3.18.1

**Comment by engram-design** [comment]
Fixed in [1.2.0](https://github.com/verbb/comments/releases/tag/1.2.0).
