### ISSUE TITLE
After updating to 1.2.0 comments can't be posted

### ISSUE THREAD

**Issue by gglnx** [verbb/comments#146]
### Description

After upgrading to 1.2.0 posting new comments doesn't work anymore. I get following error message:

> Argument 1 passed to craft\services\Elements::getElementById() must be of the type int, null given, called in /vendor/verbb/comments/src/elements/Comment.php on line 681

### Steps to reproduce

1. Update from 1.1.10 to 1.2.0
2. Try to post a comment

### Additional info

- Plugin version: 1.2.0
- Craft version: Craft Pro 3.3.19

**Comment by engram-design** [comment]
Sorry about that, fixed in [1.2.1](https://github.com/verbb/comments/releases/tag/1.2.1)
