### ISSUE TITLE
Asked Feature add assets

### ISSUE THREAD

**Issue by Fakhri17** [verbb/comments#151]
### Description

can add a assets in comments body?

because i need a feature add assets in this comments

### Additional info

- Plugin version: 1.2.3
- Craft version: 3.3.20.1

**Comment by engram-design** [comment]
Added in [1.3.1](https://github.com/verbb/comments/releases/tag/1.3.1), now supports custom fields on comments. You'll need to do your own templating on the front-end, following the [docs](https://verbb.io/craft-plugins/comments/docs/template-guides/custom-form).

However, asset-uploading is currently not supported at the moment.

**Comment by codyjames** [comment]
Would love to easily add an asset field to the comment form. Any way we can support the creation of this?

**Comment by cakleimeier** [comment]
Has there been any movement on the ability to add asset uploading to the Comment form?

**Comment by engram-design** [comment]
Added support for this in [1.5.0](https://github.com/verbb/comments/releases/tag/1.5.0), along with a few more changes with custom fields.

**Comment by codyjames** [comment]
@engram-design We suuuuuper appreciate this!
