### ISSUE TITLE
SQL State Error

### ISSUE THREAD

**Issue by theskyfloor** [verbb/comments#159]
### Description

Copy Stacktrace Search Stackoverflow Search Google Exception
Database Exception – yii\db\Exception

SQLSTATE[42803]: Grouping error: 7 ERROR: column "entries.sectionId" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...."type", "comments"."ownerId", "content"."title", "entries"....
^
The SQL being executed was: SELECT "elements"."id", "elements"."type", "comments"."ownerId", "content"."title", "entries"."sectionId", "elements"."dateDeleted"
FROM "elements" "elements"
INNER JOIN "content" "content" ON "content"."elementId" = "elements"."id"
INNER JOIN "comments_comments" "comments" ON "comments"."ownerId" = "elements"."id"
LEFT JOIN "entries" "entries" ON "comments"."ownerId" = "entries"."id"
WHERE "elements"."dateDeleted" IS NULL
GROUP BY "ownerId", "title", "elements"."id"
LIMIT 25
Error Info: Array
(
    [0] => 42803
    [1] => 7
    [2] => ERROR:  column "entries.sectionId" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...."type", "comments"."ownerId", "content"."title", "entries"....
                                                             ^
)
↵
Caused by: PDOException

SQLSTATE[42803]: Grouping error: 7 ERROR: column "entries.sectionId" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...."type", "comments"."ownerId", "content"."title", "entries"....
^

in /home/forge/url.com/vendor/yiisoft/yii2/db/Command.php at line 1290

### Steps to reproduce

1. Browse to comments area in CP
2.

### Additional info

- Plugin version: 1.3.4
- Craft version: 3.4.5

**Comment by engram-design** [comment]
Are you using MySQL or Postgres, and if so, what versions?

**Comment by theskyfloor** [comment]
PostgreSQL 10.11

**Comment by engram-design** [comment]
Fixed in [1.3.5](https://github.com/verbb/comments/releases/tag/1.3.5)

**Comment by theskyfloor** [comment]
Thanks for the quick fix!
