### ISSUE TITLE
Can't view parent comments in CP

### ISSUE THREAD

**Issue by Coalescent** [verbb/comments#160]
### Description

When attempting to view a comment in the CP, which has replies, I get the error in the screen below.

![Screen Shot 2020-02-25 at 1 41 59 PM](https://user-images.githubusercontent.com/6394091/75290137-a28c2c00-57d4-11ea-945e-32f06f7b8304.png)

### Steps to reproduce

1. Install Craft and Comments, set up them up on the front end via the default `render` method.
2. Submit and approve a comment - and then a reply.
3. Attempt to view the parent comment in the CP.

### Additional info

PHP version 7.3.8
MySQL 5.7.26
Craft Pro 3.4.6.1
Comments 1.3.5

**Comment by engram-design** [comment]
Fixed in [1.3.6](https://github.com/verbb/comments/releases/tag/1.3.6)
