### ISSUE TITLE
Error when voting/flagging as anonymous

### ISSUE THREAD

**Issue by Coalescent** [verbb/comments#161]
### Description

UI for voting and flagging shows up by default whether a user is logged in or not. If they are not logged in and try to vote or flag a comment, I get `undefined` returned in the UI (see screen) and the following 503:

`comments.js?v=1582659728:1 POST https://local.bu.com/index.php?p=actions/comments/comments/vote 503 (Service Unavailable)`

![Screen Shot 2020-02-25 at 1 40 39 PM](https://user-images.githubusercontent.com/6394091/75290667-a2d8f700-57d5-11ea-926c-9527e4cd60e9.png)

I'm just using the default templates and the `render` method on my templates. Also, this is jsut a trial - but I don't think that would make a difference.

So, the question here is, should that UI be hidden - or should some other string be returned like `You must be logged in to... whatever`.

### Steps to reproduce

1. Attempt to vote/flag as a guest

### Additional info

PHP version 7.3.8
MySQL 5.7.26
Craft Pro 3.4.6.1
Comments 1.3.5

**Comment by engram-design** [comment]
Actually, those functions shouldn't appear for guest users. But, as I've now allowed the option to vote/flag for guests, this has also been fixed in [1.3.6](https://github.com/verbb/comments/releases/tag/1.3.6)
