### ISSUE TITLE
Reply Notifications - not sending and uncertain about the logged event for this

### ISSUE THREAD

**Issue by Coalescent** [verbb/comments#162]
### Description

Just testing your plugin for a project and am not certain about a log event:

```
[info][comments] Prepare Reply Notifications.
[info][comments] Cannot send reply notification: Commenter # same as author #.
```

I'm not certain what `Commenter # same as author #.` refers to for each person?

I'm not getting reply notifications at all - and would have thought I would. I'm not logged into Craft at all, so am uncertain what this is keying off of. I am using different emails for the parent and reply comments - and 'auto subscribe' is turned on in the admin.

Wait, as I write this, is there a chance that the plugin does not send reply notifications if the users are guests?! I'm hoping not... that would seem to be a really poor shortcoming in the plugin.

And lastly, if I'm following your logs correctly (and maybe I'm not but...), it appears that the notification above is triggered as soon as the reply is submitted by the user - and not after such a reply is approved by a moderator. That seems a poor choice, no? If a moderator decides a comment is not ok for public viewing then I'd hope it would not have gone to other people on the thread.

### Additional info

PHP version 7.3.8
MySQL 5.7.26
Craft Pro 3.4.6.1
Comments 1.3.5

**Comment by engram-design** [comment]
You're actually correct on your first assumptions here, reply notifications weren't being sent when both the replied-to comment and the reply comment were both by guest users.

And the moderation check is done just a few lines below this logging, which I've just moved up earlier in the process to prevent confusion. Notifications should also be firing when a moderated comment is approved.

Updated in [1.3.6](https://github.com/verbb/comments/releases/tag/1.3.6)
