### ISSUE TITLE
Javascript error on IE/Edge browsers

### ISSUE THREAD

**Issue by Coalescent** [verbb/comments#163]
### Description

I am getting the same error (see below) on IE 11 and Edge browsers (other browsers are fine).

![Screen Shot 2020-02-25 at 6 54 35 PM](https://user-images.githubusercontent.com/6394091/75307666-26f4a400-5801-11ea-859d-312255f14058.png)

I am outputting comments using `{{ craft.comments.render(entry.id) }}` and using the built-in CSS and JS.

I am getting this result on a totally stripped back template that only contains some simple boilerplate HTML and does not load **any** other resources of any kind.

The only other item to note is in my tests I'm using a self-signed cert so the page isn't secure and there's an expected cert warning - but I wouldn't imagine that would have any effect.

### Steps to reproduce

1. Set up a template to render comments
2. Test in IE 11 or Edge.

### Additional info

PHP version 7.3.8
MySQL 5.7.26
Craft Pro 3.4.6.1
Comments 1.3.5

**Comment by engram-design** [comment]
Fixed in [1.3.6](https://github.com/verbb/comments/releases/tag/1.3.6)
