### ISSUE TITLE
Votes incorrect when hitting downvote threshold

### ISSUE THREAD

**Issue by Coalescent** [verbb/comments#164]
### Description

When a comment hits the downvote threshold, the voting count seems to switch to a positive upvote number. See the screen below... the Downvote threshold is set to `2`. The comment has received 2 downvotes and no upvotes, so the comment is hidden as expected. However, the count now shows it as 2 positive upvotes.

![Screen Shot 2020-03-02 at 10 03 06 AM](https://user-images.githubusercontent.com/6394091/75704400-29765400-5c6e-11ea-976e-7930c3604c50.png)

Lastly, just a couple UX thoughts...

When a comment hits that downvote threshold, the voting UI is still in place and usable. I'm not certain what benefit this provides since a user cannot see the comment anymore to judge whether it is good or bad. Could consider hiding it in such a case and just showing the downvote total?

It does not appear that down, up and flags totals are shown in the CP UI for each comment (at least, I can't seem to see them). I could see that being very useful for moderators to decide to possibly trash such comments of take other actions.

### Steps to reproduce

1. Downvote a comment to its threshold

### Additional info

PHP version | 7.3.8
Darwin 18.7.0
MySQL 5.7.26
Craft edition & version | Craft Pro 3.4.9
Comments | 1.3.6

**Comment by engram-design** [comment]
Yep, so technically this is more of a UI issue, in that the number shown isn't supposed to be the number of upvotes and then also showing downvotes - its the total number of votes. So if you have 5 upvotes and 2 downvotes, that number should show 3.

But, you are correct - there's an error on that anyway, where votes are incorrectly shown as positive in any case.

With regards to hiding the voting controls once the threshold has been reached, its really just there in case people want to revoke their downvotes. I'm not sure about hiding that by default, so I've added that as a config option - `hideVotingForThreshold`

Added votes/flag in the CP!

See [1.3.7](https://github.com/verbb/comments/releases/tag/1.3.7)
