### ISSUE TITLE
PHP 7.2+ count() warnings/errors

### ISSUE THREAD

**Issue by tonyclemmey** [verbb/comments#165]
### Description
PHP 7.2+ count() warnings

Backward incompatible changes - Manual - PHPwww.php.net › manual › migration72.incompatible.php
Warning: count(): Parameter must be an array or an object that implements Countable in %s on line %d Warning: count(): ... In the next major version of PHP, they will generate Error exceptions. ... Migrating from PHP 7.1.x to PHP 7.2.x.

### Steps to reproduce

1. PHP 7.2 or above 
2. Verbb Comments Plugin

### Additional info

- Plugin version: @latest
- Craft version: 2 @latest

**Comment by engram-design** [comment]
Comments for Craft 2 is no longer supported, sorry. There are no plans to add this support, and is fixed in the Craft 3 version of Comments.
