### ISSUE TITLE
No Avatar image for 'logged in' users

### ISSUE THREAD

**Issue by terryupton** [verbb/comments#167]
### Description
Hi Josh, just installed this plugin and using the default theme/templates, I am having problems with logged in (CMS admin) users profile images not showing up.
Here are some screenshots to help illustrate.

**Front-end:**
<img width="917" alt="Screenshot 2020-03-16 at 15 21 00" src="https://user-images.githubusercontent.com/5698596/76773347-3af54b00-679a-11ea-9818-19ae9fb7828d.png">

**Dev Tools:**
<img width="730" alt="Screenshot 2020-03-16 at 15 20 54" src="https://user-images.githubusercontent.com/5698596/76773353-3cbf0e80-679a-11ea-817a-8c65e3bb72b7.png">

**Source Code:**
<img width="1613" alt="Screenshot 2020-03-16 at 15 25 13" src="https://user-images.githubusercontent.com/5698596/76773446-5fe9be00-679a-11ea-9cc5-b67b04344444.png">

It is placing the image src as empty. 

### Steps to reproduce

1. Log into the CMS
2. Leave a comment

### Additional info

- Plugin version: 1.3.7
- Craft version: Craft Pro 3.4.9

**Comment by engram-design** [comment]
So this should be using the users' photo from their account. Can you confirm if there is an image on this account, and if so, what file format? I've tested on my end with JPG's and they seem to work. File format's in theory shouldn't matter though.

**Comment by terryupton** [comment]
the account in question is mine, as I have just been testing before releasing to the client.
I am the main admin. The image is a jpg. However, I have just realised this was a Craft 2 > Craft 3 update and having checked the location of image, it resides at  `/cpresources/d9f96877/terry-sq-avatar-casual-beard-2019.jpeg?v=1584610313`

(please don't judge the filename :-))

I have now changed this to use a folder inside my uploads and changed the toggle to make these assets public urls (Assets in this volume have public URLs) and this has resolved the issue.

Perhaps my only comment would be that if comments cannot access an image (be that the permissions link) or location - it should either display an error or fallback to the placeholder avatar. 

Feel free to close this issue though and thanks for looking into this for me.

**Comment by engram-design** [comment]
Yep, I'll put in some additional checks to cater for this sort of case. Thanks!

**Comment by engram-design** [comment]
Fixed in [1.7.0](https://github.com/verbb/comments/releases/tag/1.7.0)
