### ISSUE TITLE
Auto subscribe every user who comments on post

### ISSUE THREAD

**Issue by cookie10codes** [verbb/comments#172]
### Description
Hi devs! I need a prop to set auto subscribe on a comment just like the facebook comments functionality on a post. So when user x comments on a post, the author of the post gets a notification email. When user y comments after user x his post, the author and user x should receive a notification email.

This will also need an event like these https://verbb.io/craft-plugins/comments/docs/developers/events#notification-related-events. Is this possibile?

Thanks for looking into this!

**Comment by engram-design** [comment]
Added `notificationSubscribeAuto` in [1.3.8](https://github.com/verbb/comments/releases/tag/1.3.8). Note that this will only work for registered users at this stage.
