### ISSUE TITLE
Confusing fields in default template when anonymous comments are disabled

### ISSUE THREAD

**Issue by jsunsawyer** [verbb/comments#178]
### Description
With `Allow anonymous comments` disabled, `Your Name` and `Email` fields still display, even though this setting makes it so that a user must be logged in to comment.

It seems that disabling anonymous comments is more of a require login setting. Is this correct?

![Screen Shot 2020-05-06 at 3 19 56 PM](https://user-images.githubusercontent.com/1007191/81234168-16a13800-8fad-11ea-816e-295cde331f1c.png)

Testing guest comment
![Screen Shot 2020-05-06 at 3 19 46 PM](https://user-images.githubusercontent.com/1007191/81234181-1c971900-8fad-11ea-9932-8e814e6620a7.png)

### Additional info

- Plugin version: 1.3.12
- Craft version: 3.4.17.1

**Comment by engram-design** [comment]
The `Require email and name for guests` field makes them `required` for a comment submission. It still shows the fields, as I feel its pretty important information to have. I suppose I should introduce another settings for `Show email and name for guests`

With `Allow anonymous comments` the comments form will still show, but you won't be able to submit a comment if you're a guest. I suppose the form shouldn't be shown altogether?

**Comment by jsunsawyer** [comment]
I was just a bit confused by the `Name` and `Email` fields showing up when they're irrelevant given existing settings. `Allow anonymous comments` being disabled seems like it should remove these. The fields existing made me think that they would still allow for "guest" comments. To me, "anonymous" is a person without a name or email added.

I'll probably adjust accordingly in a custom template, but wanted to be sure I understood these settings and note that there might be an issue with the current default template.

**Comment by engram-design** [comment]
Yeah, I can see how its confusing. I suppose I should refrain from using "Anonymous" and use "Guest" instead. I don't really want to encourage truly anonymous comments (where its literally just the comment text and no author name/email), but I suppose that might be a valid use-case.

I think I'll rename "Anonymous" to "Guest".

Then, I think I'll add a `Show email and name for guests` option as well, so you can turn this off if you'd like. Sound okay?

**Comment by engram-design** [comment]
This has been updated in [1.4.0](https://github.com/verbb/comments/releases/tag/1.4.0)

**Comment by jsunsawyer** [comment]
@engram-design Things are more clear with the updated wording, but I think it'd also make sense to make it so the default template only shows the name and email fields if `Allow guest comments` is enabled, regardless of the `Show email and name for guests` option.

Currently, options can be set up so that these fields exist on the front-end, but still require the user to be logged in – making them useless.

**Comment by engram-design** [comment]
I've updated this so that if either `Show email and name for guests` or `Require email and name for guests` these fields are shown on the front end, as well as some nicer UI in the control panel.

We wouldn't want to show the name and email fields if just `Allow guest comments` was enabled, because we might not want to show those fields, even for guests. Sometimes, people don't care about name and emails for guests.

Updated in [1.4.1](https://github.com/verbb/comments/releases/tag/1.4.1)

**Comment by jsunsawyer** [comment]
@engram-design Just tested. I'm still not sure it's behaving like you'd want.

In `_special/form.html` on line 26, would changing `{% if not currentUser and (settings.guestShowEmailName or settings.guestRequireEmailName) %}` to `{% if not currentUser and settings.allowGuest and (settings.guestShowEmailName or settings.guestRequireEmailName) %}` make more sense?

What's happening is that when `allowGuest` is disabled, but its child settings are still enabled, the fields still get rendered.

**Comment by engram-design** [comment]
Hmm, it could be argued that the whole form shouldn't be shown when `settings.allowGuest` is disabled, but maybe that's too much a change in behaviour?

Otherwise, yes you're correct.
