### ISSUE TITLE
FR: Auto post comment to social media 

### ISSUE THREAD

**Issue by johanneslamers** [verbb/comments#18]
Give your commenters the option to send a simultaneous tweet or facebook post when they post a comment. It's a great way to let your commenters spread the word about your site and drive new traffic and comments!

**Comment by engram-design** [comment]
FYI, this is on the long-term roadmap, as its pretty involved, so no movement on this right now.

**Comment by engram-design** [comment]
Going to mark this as closed, because this is very, very unlikely to get done.
