### ISSUE TITLE
Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them. Inside  /vendor/verbb/comments/src/templates/_special/comment.html:125

### ISSUE THREAD

**Issue by terryupton** [verbb/comments#180]
### Description
It appears that there are some deprecation errors inside the /vendor/verbb/comments/src/templates/_special/comment.html:125

```
1. in /Users/terryupton/Dropbox/Amasci/Websites/The MBR Site V2/thembrsite.com/vendor/verbb/comments/src/templates/_special/comment.html at line 125
        <div data-role="reply"></div>
 
        <div data-role="errors" class="cc-e"></div>
        <div data-role="notice" class="cc-n"></div>
 
        <div data-role="replies">
            {% if comment.children | length %}
                {% for nestedComment in comment.children.all() %}
                    {% include 'comment' with { comment: nestedComment } %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</article>
```

### Additional info

- Plugin version: 1.5.4
- Craft version: Craft Pro 3.4.20

**Comment by engram-design** [comment]
Are you sure you're on 1.5.4? Refer to https://github.com/verbb/comments/blob/419b08c85a904e4b4fde9d8089e59ed317ec69a2/src/templates/_special/comment.html#L123-L129 which is tagged in 1.5.4.

This was changed recently to not include `.all()` because we're using eager-loading by default. If you're using custom templates, you'll need to update your templates.

**Comment by terryupton** [comment]
Hi Josh,
I have just run an update as I saw some critical updates.
- comments 1.5.4 => 1.5.6 (CRITICAL)

It looks like I was on 1.5.4 but I am no longer seeing these deprecation errors, so I am not entirely sure as to what occurred for me to see these, as I was definitely seeing them after updating to 1.5.4. Sorry for any inconvenience caused. Looks ok now. I will go ahead and close this ticket.
