### ISSUE TITLE
Exception after upgrading php to 7.4

### ISSUE THREAD

**Issue by kringkaste** [verbb/comments#181]
### Description

After upgrading the Server from php 7.0 to 7.4, the following Exception is thrown in the frontend when rendering the comment template:

yii\base\ErrorException: get_class() expects parameter 1 to be object, null given in /local/vendor/verbb/comments/src/services/CommentsService.php:710
Stack trace:
#0 /local/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError()
#1 [internal function]: craft\web\ErrorHandler->handleError()
#2 /local/vendor/verbb/comments/src/services/CommentsService.php(710): get_class()
#3 /local/vendor/verbb/comments/src/services/CommentsService.php(210): verbb\comments\services\CommentsService->_checkOwnerFieldEnabled()
#4 /local/vendor/verbb/comments/src/models/Settings.php(105): verbb\comments\services\CommentsService->checkClosed()
#5 /local/vendor/twig/twig/src/Extension/CoreExtension.php(1499): verbb\comments\models\Settings->canComment()
#6 /local/vendor/craftcms/cms/src/helpers/Template.php(96): twig_get_attribute()
[...]

The issue was first seen on 1.2.4 with Craft 3.3.20.1, then we upgraded to 1.5.5 on Craft 3.4.20 and it still throw this exception.

### Steps to reproduce

1. {{ craft.comments.render(entry.id) }}

### Additional info

- Plugin version: > 1.2.4
- Craft version: > 3.3.20.1

**Comment by engram-design** [comment]
Fixed in [1.5.6](https://github.com/verbb/comments/releases/tag/1.5.6)
