### ISSUE TITLE
Error message in actionSave method is not translated

### ISSUE THREAD

**Issue by dreamseeker** [verbb/comments#182]
### Description

When posting a blank comment, the error message is not translated.

So, I solved it as follows:

https://github.com/verbb/comments/blob/craft-3/src/controllers/CommentsController.php#L120-L122

```
$comment = $this->_setCommentFromPost();

// override currentSite
$siteService = Craft::$app->getSites();
$siteService->setCurrentSite($comment->siteId);

if (!Craft::$app->getElements()->saveElement($comment, true, false)) {
```

### Steps to reproduce

1. Create a multi-site like [ `ja`, `en`] with CP.
2. Create a translation file for each site.
3. Browse the frontend comment page.
4. Post a blank comment.
5. Each site outputs the same error message. it seems a translation meesage of the primary site.

### Additional info

- Plugin version: 1.6.0
- Craft version: 3.4.22.1

**Comment by engram-design** [comment]
Hmm, that's strange, I've setup two sites for testing - one uses `en-AU` on the primary site and the other `en-CA`. I'm sure this would be fine for any other language.

I've created a file `translations/en-CA/comments.php` with:
```
<?php

return [
    'Comment must not be blank.' => 'SOME OVERRIDE TEXT',
];
```

Which results in the correct translation being shown on the respective site. This on the primary english site:

![Screen Shot 2020-05-31 at 2 28 38 pm](https://user-images.githubusercontent.com/1221575/83344492-0fbada80-a34b-11ea-89d7-2f597d9f67ae.png)

And this on the en-CA site:
![Screen Shot 2020-05-31 at 2 26 54 pm](https://user-images.githubusercontent.com/1221575/83344494-177a7f00-a34b-11ea-94b5-b57cf8b0c279.png)

**Comment by dreamseeker** [comment]
Hi Josh.
Thank you for testing.

I added only the `Comments` plugin to my clean installed Craft CMS.
Then I tried again in the same way as you did.

However, the translation was not applied to the `en-CA` site.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/548326/83348563-ec068d00-a368-11ea-9236-a2bf6c274e21.png">

It seems that the smallest ID in the actionUrl is treated as the current site regardless of whether it is primary or not.

It may be just my problem, I will continue to investigate.

**Comment by engram-design** [comment]
Hmm, that's interesting. Are you using any custom templates, or have the default CSS/JS turned off? Just want to ensure I can replicate your setup as well.

Can you clarify what you mean by "smallest ID in the actionUrl'? Do you mean the siteId in the actionUrl?

**Comment by dreamseeker** [comment]
> Are you using any custom templates, or have the default CSS/JS turned off?

No.
I tried with the default settings.

For reference, I attach zip archives such as composer.json and project.yaml.
[project_sample.zip](https://github.com/verbb/comments/files/4708697/project_sample.zip)

> Can you clarify what you mean by "smallest ID in the actionUrl'?

Sorry.
In the following cases, the error message will be Japanese in Case 1 and French in Case 2:

### Case 1

| Site ID | Name | Handle | Language | Primary |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 1 | site-A | default | ja | Yes |
| 2 | site-B | en_ca  | en-CA |  |

### Case 2

| Site ID | Name | Handle | Language | Primary |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 3 | site-A | default | fr | |
| 4 | site-B | en_ca  | en-CA | Yes |

Therefore, I thought that the current `Site ID` was not passed to the controller action (`/index.php?p=actions/comments/comments/save`).

**Comment by engram-design** [comment]
If you're using the default behaviour, it should be firing off save requests via ajax, and it should include a payload similar to the below:
```
action: comments/comments/save
elementId: 2460
siteId: 4
```

You'll see that it includes the siteId, which I think might be missing in this instance.

**Comment by dreamseeker** [comment]
I'm using the default behavior and the following JSON code is an example of outputting `$request->post()` from within the `actionSave` method.

```
{
  "action": "comments/comments/save",
  "elementId": "9",
  "siteId": "2",
  "newParentId": "",
  "commentId": "",
  "CRAFT_CSRF_TOKEN": "XXXX",
  "__UAHOME": "XXXX",
  "__UAHASH": "XXXX,
  "beesknees": "",
  "__JSCHK": "XXXX",
  "fields": {
    "comment": ""
  }
}
```

I think this is the expected state.

However, Error message still doesn't get translated.
This may be due to my environment.

So, I'll try another way that doesn't use the default behavior.

I appreciate your advice.
Thanks.

**Comment by engram-design** [comment]
Thanks for the info - still looking into it!

**Comment by engram-design** [comment]
I cannot reproduce this no matter what I do! If it's still an issue, let me know. Ideally, if you can shoot through a zip of your database and entire project, that'd really help try to get it _not_ working on my end.
