### ISSUE TITLE
Feature Request to allow a 'notification admin' email address

### ISSUE THREAD

**Issue by terryupton** [verbb/comments#184]
### Description
Hi Josh, I have a situation where several posts are assigned to one author (me when I. built the site) and several tot he client. At the moment I cannot see an easy way to re-assign the author in Craft, but I am looking. However, I wondered whether it would perhaps be a nice addition to be able to set a 'admin' (or an array of email addresses) for all comments, that receives a notification
when a new comment is added. As this would solve this issue, but I also see this as a valid use case as often there will be perhaps 1 or 2 people, responsible to moderate and manage the comments, these might not be the authors themselves, or as mentioned this might be split across multiple authors.

Is this something fairly easy to add and would you consider?

**Comment by engram-design** [comment]
Added in [1.8.0](https://github.com/verbb/comments/releases/tag/1.8.0)
