### ISSUE TITLE
Can't delete comment. "Uncaught TypeError" fresh install

### ISSUE THREAD

**Issue by tom-byrom** [verbb/comments#185]
### Description
When trying to press the delete button I get the following error 

![Annotation 2020-06-14 145819](https://user-images.githubusercontent.com/34626292/84595396-8ed20780-ae4f-11ea-941c-101278182ebe.png)

### Steps to reproduce

1. Just installed the comments plugin, copied the example config file. 
2. Added the default twig tag to show comments and form.

### Additional info

- Plugin version: Latest
- Craft version: Latest

**Comment by engram-design** [comment]
Fixed in [1.6.2](https://github.com/verbb/comments/releases/tag/1.6.2)
