### ISSUE TITLE
Missing script tag for inline JS

### ISSUE THREAD

**Issue by john-henry** [verbb/comments#187]
Hi Josh,

thanks for the update1.6.3. It will be really helpful

Bit of a stumbling block though. I think there are script tags missing from https://github.com/verbb/comments/blob/craft-3/src/variables/CommentsVariable.php#L63 

I have a PR [here](https://github.com/verbb/comments/pull/186) if I am correct 

- Plugin version:1.6.3
- Craft version: 3.4.24

**Comment by engram-design** [comment]
Whoops, what a rookie move! Thanks 👍

See [1.6.4](https://github.com/verbb/comments/releases/tag/1.6.4)
