### ISSUE TITLE
[FR] The Scunthorpe Problem

### ISSUE THREAD

**Issue by jsmrtn** [verbb/comments#190]
### Description

Hitting the [Scunthorpe Problem](https://en.wikipedia.org/wiki/Scunthorpe_problem) when using the comment moderation/spam/banned lists. 

Would it be possible to add exact matching into the block lists, perhaps how Google does by wraping the word in quotes. i.e. ass at the moment would block assessment, but if you put in "ass" it wouldn't.

Thanks!

**Comment by engram-design** [comment]
Added in [1.8.0](https://github.com/verbb/comments/releases/tag/1.8.0)
