### ISSUE TITLE
Loading comments form via Ajax and Comments JS not working as expected

### ISSUE THREAD

**Issue by tom-byrom** [verbb/comments#191]
### Description
When used as a Reactive component via [Sprig](https://plugins.craftcms.com/sprig) when clicking any of the links using the standard comment template, like reply, edit for example it just acts like a normal anchor link and not the expected behaviour.

The reason I want to use it as a reactive component, for example when the user clicks ' View Comments' only then does it render the comments.  Is because if I just use the standard template tag `{{ craft.comments.render(entry.id) }}` this creates about 60+ database queries and increases TTFB by about 40% on a fast server....

So I want to offset all these initial comment related queries because comments will be at the bottom of post and might not even get read but creates a performance overhead thats just not necessary on page load.

Problem is that I think this creates issues with the JS, although I'm not getting errors it's just the links work like normal anchors and they don't do what they're supposed too, like change the inputs etc.

I'm rendering the CSS and JS within the Sprig component after the  comment form tag. 

In my entry template

```
{% set id = entry.id %}
{{ sprig('components/comments/comments', { entryId: id }) }}`
```

Sprig component which gets rendered
```
{% if not sprig.request %}

<a sprig s-target="#commentswrapper" id="viewComments">View comments</a>

<div id="commentswrapper">
</div>

{% else %}


{{ craft.comments.render(entryId) }}

{{ craft.comments.renderCss(entryId) }}

{{ craft.comments.renderJs(entryId) }}

{% endif %}

```

**Comment by engram-design** [comment]
I've not yet caught up with Sprig, so I'll have to do some specific testing with this setup. It's very possible I'll need to make allowances for Comments JS to cater for this scenario.

**Comment by tom-byrom** [comment]
I did have a look at your Comments JS and it just went over my head! But I assumed the same as you.

Would be cool though and a big performance boost. I got some inspiration from how Medium present their comments which is you click the comment icon and it opens a side draw with all the comments.

Was hoping to do something a little similar and defer all the initial queries unless someone actually wants to read or add comments. As the performance boost was quite significant

**Comment by engram-design** [comment]
As an alternative, you could ajax-load the template partial that contains the template tags and JS, without needing to use Sprig?

**Comment by tom-byrom** [comment]
Thanks - I'm giving that a go but I'm facing an issue because I need to pass the entry.id to the include so it can be used in the comments twig filter.

Do you know how that's possible?

**Comment by tom-byrom** [comment]
So I managed to get the ajax working and passing over the entry.id, but I get the exact same issue as using Sprig, which actually isn't much of a surprise as Sprig just loads it over Ajax as well! 

So don't think this is possible out the box with the standard Comment JS file.....

Code if you wanna test yourself:

**Entry**
```
<section id="commentsBlock" class="comments mb-5">

       <button onclick="loadDoc()" class="btn btn-primary">Load Comments</button>

</section>

{% set entryId = entry.id %}

        <script>
            function loadDoc() {
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                document.getElementById("commentsBlock").innerHTML =
                this.responseText;
                }
            };
            xhttp.open("GET", "/includes/comments?id="+{{ entryId }}, true);
            xhttp.send();
            }
        </script>

```

**Comments include**

```
{% set entryId = craft.app.request.get('id') %}

{{ craft.comments.renderCss(entryId) }}

{{ craft.comments.render(entryId) }}

{{ craft.comments.renderJs(entryId) }}
```

**Comment by tom-byrom** [comment]
Managed to get this working now guys after the latest update an the newly added craft.comments.getJsVariables.

Cheers

**Comment by leevigraham** [comment]
@tom-byrom Can you share a working example?

**Comment by leevigraham** [comment]
Related: https://verbb.io/craft-plugins/comments/docs/template-guides/available-variables#craft-comments-getJsVariables

**Comment by tom-byrom** [comment]
@leevigraham Took me a while to do this but it does work. So the problem was/is not being able to execute Javascript that is loaded via Ajax/Fetch API etc. So we need to do all the Javascript executing on the original document and not any content that's loaded in.

On the index page I have a feed of entries that when clicked on will open the entry in a section that slides in without reloading the page. So in my case I render the Comments JS on the index page and I create a ``commentsInit() `` function for initialising  the comments. 

I then have a couple of includes, one for the entry content and a separate one just for the comments.

In the entry include I create the comments query and a comments JS variables query (the new feature), I then populate a hidden field with that information so I can then use it outside of this template. This template is also where I have a 'load comments' button.

The comments include simply renders the comments block when you click 'load comments'.

``commentsInit()`` function is called whenever an entry is clicked and after that entry content partial has loaded in via a fetch request.  It creates an event listener on the button to load comments, so when clicked it pulls in the comments include.

The ``commentsInit()`` basically gets the hidden variables I created from ``<span id="commentsVariables" style="display: none;">{{ jsVariables.settings | json_encode | raw }}</span`` in plain text and parses it to JSON it then uses this as part of creating a new comments instance with all the correct messages for that particular entry.
 
### Main index page which dynamically pulls in entries when they are clicked on

``{{ craft.comments.renderJs(0, {}, false) }}``

```
function commentsInit() {
    let entry = document.querySelector('#entry')
    let entryId = entry.dataset.entryid
    let commentsVariable = document.querySelector('#commentsVariables')
    let commentsContent = commentsVariable.textContent
    let myJSON = JSON.parse(commentsContent)
    let loadComments = document.querySelector('#loadComments')
    loadComments.addEventListener('click', function(){
        fetch("/includes/comments-home")
            .then((response) => {
                return response.text();
            })
            .then((html) => {
                document.querySelector('#commentsBlock').innerHTML = html
                let commentsBlock = document.querySelector('#commentsBlock')
                let commentsId = commentsBlock.firstElementChild.id;
                let commentsIdfull = "#" + commentsId
                new Comments.Instance(commentsIdfull, myJSON);
            });
    })
}
```

### Entry content partial
```
//Comments Query
{% set commentsQuery = craft.comments.fetch()
.owner(entry)
.all() %}

//Button to load in comments
<button id="loadComments" class="btn btn-primary">Load {{ commentsQuery|length }} Comments</button>

// CSS to render from comments
{{ craft.comments.renderCss(entryId) }}

//Comments JS variables Query
{% set jsVariables = craft.comments.getJsVariables(entryId) %}

//Needed to then get the JS variables for the entry (populating a hidden html tag)
<span id="commentsVariables" style="display: none;">{{ jsVariables.settings | json_encode | raw }}</span>

```

### Comments include
```
{% set fullUrl = craft.app.request.headers.get('referer') %}

{% set slug = fullUrl | split('/') | last %}

{% set entry = craft.entries.section('posts').slug(slug).one() %}

{% set entryId = entry.id %}

{{ craft.comments.render(entryId) }}
```

**Comment by leevigraham** [comment]
I settled on something similar using stimulus.js

Primary Template:

```html
    <div class="mt-8">
        <h2>Comments</h2>
        <div
            data-controller="comments"
            data-comments-config-value="{{ craft.comments.getJsVariables(entry.id)|json_encode }}"
            data-comments-url-value="{{ url('comments/load', {elementId: entry.id}) }}"
        >
            <p>Fetching Comments…</p>
        </div>
    </div>
```

Ajax loaded template:

```html
{{ craft.comments.render(craft.request.getQuery('elementId')) }}
{% if not currentUser %}
    <p class="">
        <a href="{{ loginUrl }}" class="btn-primary my-4">
            <span class="btn-label">Login to post a comment</span>
        </a>
    </p>
{% endif %}
```
Stimulus Controller:

```js
import { Controller } from 'stimulus';

export default class extends Controller {

    static values = {
        config: Object,
        url: String,
    };

    connect () {
        this.element[this.identifier] = this;
        const element = this.element;
        window.MTL.fetchState()
            .then(state => {
                const method = 'GET';
                const action = this.urlValue;
                fetch(action, { method, action })
                    .then(response => response.text())
                    .then(html => {
                        element.innerHTML = html;
                        this.configValue.settings.csrfToken = state.csrfToken.value;
                        new window.Comments.Instance(this.configValue.id, this.configValue.settings);
                    })
                    .catch(error => {});
            });

    }
}
```
