### ISSUE TITLE
Comments for Craft Commerce products?

### ISSUE THREAD

**Issue by ghost** [verbb/comments#193]
**What are you trying to do?**

I am looking at the Comments plug-in for a project, and it looks great ... but the documentation doesn't list Commerce Products (or would it more accurately be purchasables/variants?) as an element type in the Permissions section. And I really need them for a new project, if possible.

Can you tell me if they're supported, please? And if not, are there any plans to add this feature?

Thanks heaps!

**Comment by engram-design** [comment]
The permissions are just there for fine-grained control. By default, you can comment on any element no matter what, including Products or Variants. Permissions are just there for those other elements to restrict based on their groupings (section, group, etc).

In fact, the [docs](https://verbb.io/craft-plugins/comments/docs/feature-tour/permissions) mention this:

> By default, comments are enabled for all elements.

You can also use the Comments fieldtype to setup permissions, if you just want a few products/variants to enable commenting on as well.

I'll look at adding permissions for Commerce product types soon.

**Comment by ghost** [comment]
Great, thanks. Sorry I didn't catch that bit of the notes!
