### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by piotrpog** [verbb/comments#200]
Here is some formatting issue:
https://verbb.io/craft-plugins/comments/docs/developers/events

![image](https://user-images.githubusercontent.com/42622545/93500081-1f6b2880-f914-11ea-9b73-7ac32fcb153e.png)

Also, docs mention `beforeSaveComment` here:
https://verbb.io/craft-plugins/comments/docs/developers/events#the-beforeSaveComment-event

but in code example there is just standard `EVENT_BEFORE_SAVE`.

**Comment by engram-design** [comment]
Formatting fixed, but what's the issue on the beforeSaveComment event? The "standard" event is indeed the event raised on every element before it is saved. It's not a Comments-plugin specific event, but it's documented for ease-of-use for other people who might not know about these events. Unless I'm missing something?
