### ISSUE TITLE
comment.trashUrl link - Post request required

### ISSUE THREAD

**Issue by piotrpog** [verbb/comments#203]
I checked out example templates that dont use JS. In this one:
https://github.com/verbb/comments/blob/craft-3/examples/html/comment.html
there is deletion link - `comment.trashUrl`.

When i tried to use this link, error messageshowed up - '`Post request required`.

**Comment by engram-design** [comment]
Right, `trashUrl` is deprecated and moreso, shouldn't be used, the example templates just weren't updated. Updated now.
