### ISSUE TITLE
Custom fields not reset when send the form

### ISSUE THREAD

**Issue by cmartinespinosa** [verbb/comments#205]
**Description**

There is a bug when I send the comment, because it doesn't reset the form in the custom fields.

**Steps to reproduce**
1. Create a custom field
2.Try to send a comment 

**Additional info**
- Plugin version: 1.6.6
- Craft version:  3.5.13.2 Pro
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Fixed in [1.7.0](https://github.com/verbb/comments/releases/tag/1.7.0)
