### ISSUE TITLE
Undefined index: path

### ISSUE THREAD

**Issue by leevigraham** [verbb/comments#207]
**Description**

Pretty sure there's an issue using S3 buckets for user avatars as they don't need a path

<img width="782" alt="image" src="https://user-images.githubusercontent.com/25124/101761073-d51ecf80-3b2f-11eb-983b-ae1276ed098a.png">

<img width="587" alt="image" src="https://user-images.githubusercontent.com/25124/101761240-00092380-3b30-11eb-8858-3a00079aa195.png">

**Additional info**
- Plugin version: 1.7.3
- Craft version: CMS 3.5.16
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Fixed in [1.7.4](https://github.com/verbb/comments/releases/tag/1.7.4)
