### ISSUE TITLE
Using shapes… pending status icon disappears

### ISSUE THREAD

**Issue by leevigraham** [verbb/comments#208]
**Description**

comments-cp.css makes the border for .status.pending transparent which is used to draw the css triangle

<img width="240" alt="image" src="https://user-images.githubusercontent.com/25124/101761898-d4d30400-3b30-11eb-90c2-deefc9792b19.png">

<img width="637" alt="image" src="https://user-images.githubusercontent.com/25124/101761997-f16f3c00-3b30-11eb-9061-77c7af29f44c.png">

**Steps to reproduce**
1. Enable 'Use shapes to represent statuses ' in user preferences
2. Review a comment

**Additional info**
- Plugin version: 1.7.3
- Craft version: CMS 3.5.16
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Fixed in [1.7.4](https://github.com/verbb/comments/releases/tag/1.7.4)
