### ISSUE TITLE
Form layout not saving any custom fields added.

### ISSUE THREAD

**Issue by rickmills** [verbb/comments#209]
I'm evaluating this plugin for use on a site I'm building and wanted to add a title and author name field. So I've set the fields up the same way you usually do in Craft's settings area, and now I've gone to the plugins Comments Form page (`https://<siteurl>/admin/comments/settings#tab-comments-form`).

However regardless of what fields I try adding to the comment form, it saves and returns back to the page with just the comment field again. 

I've checked the logs - no errors are reported. I've wiped caches, rebuilt, tried different browsers etc, it just doesn't seem to save any changes made within the form layout box. The 'Show custom field names' and 'Show custom field instructions' lightswitch fields save fine so the overall form is certainly saving.

See below for a gif showing this in action.

**Steps to reproduce**
1. Go to `/admin/comments/settings#tab-comments-form` and drag a field into the Comment Form area and press save
2. On reload the fields aren't there, despite getting a success flash message.

**Additional info**
- Plugin version: 1.7.3
- Craft version: 3.5.16
- Multi-site: No

**Additional context**
Gif showing the issue in real time:

![comment-fields-bug](https://user-images.githubusercontent.com/103707/101797721-4182da00-3b02-11eb-8e5c-f65d25fa3474.gif)

**Comment by rickmills** [comment]
I've found the issue - certainly looks to be a bug.

A record isn't created in the `fieldlayouttabs` table for the comment plugin, meaning its impossible to add custom fields.

I manually added a record to that table and linked it back to the field layout record for comments and it all works again, so looks like it's going to be something not working quite right when the plugin is installed.

**Comment by engram-design** [comment]
This might've been an issue for some time, as there was a bug (that's been around for a while) that meant field layouts weren't being created. This wasn't a problem until now where we rely on it more.

Should be improved in [1.7.4](https://github.com/verbb/comments/releases/tag/1.7.4)
