### ISSUE TITLE
Support custom fields on the FeedMe importer

### ISSUE THREAD

**Issue by rickmills** [verbb/comments#211]
**What are you trying to do?**
I've got a couple of custom fields set up on the comments and wanted to make use of FeedMe to import threaded comments into the site but when going through the FeedMe setup for a JSON feed I get no options to import custom fields, just the built in ones.

**What's your proposed solution?**
It'd be great if the plugin could fully support FeedMe.

**Comment by engram-design** [comment]
Yep, custom fields are a relatively new addition so I'll need to add support for this.

**Comment by engram-design** [comment]
Added in [1.8.0](https://github.com/verbb/comments/releases/tag/1.8.0)
