### ISSUE TITLE
<p> tag is removed from existing comment text after canceling an edit

### ISSUE THREAD

**Issue by jsunsawyer** [verbb/comments#213]
It seems that the script is removing, then re-adding the surrounding `<p>` tag that's in the template, but it's not being re-added in the `closeForm` function.

As a side note, this got me curious about my idea of utilizing markdown for comments. If I did, I don't think I'd want the content to be enclosed in a `<p>` tag.

**Comment by engram-design** [comment]
Fixed in [1.8.0](https://github.com/verbb/comments/releases/tag/1.8.0)
