### ISSUE TITLE
Flagging comments with the "Enable Flagged Notifications" setting checked returns an error

### ISSUE THREAD

**Issue by jsunsawyer** [verbb/comments#217]
**Description**
I'm getting the error `Invalid argument supplied for foreach()` upon flagging a comment.

This is inconsistent, and will successfully flag a comment after a failed attempt, but will throw the error again upon successive flagging and unflagging.

**Additional info**
- Plugin version: 1.8.3
- Craft version: 3.6.3
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [1.8.4](https://github.com/verbb/comments/releases/tag/1.8.4)
