### ISSUE TITLE
Adding comments via GraphQL

### ISSUE THREAD

**Issue by rcobiella** [verbb/comments#218]
**What are you trying to do?**

Is there currently a way (or workaround) to do this? I think the only thing available on GraphQL right now is the comments list. Is it possible to have a full comments system with headless Craft?

**Comment by engram-design** [comment]
At the moment only querying via GraphQL is supported. We'll need to add support for GQL mutations.

**Comment by maries24** [comment]
Hi @engram-design ,

Are you planning to include that feature: ability to add comments via the GraphQl API? Do you have a timeline for it? Thanks.

We're rebuilding the website of the W3C using a headless architecture. The blog has comments enabled se we really need to be able to add comments over the API. Cheers.

**Comment by engram-design** [comment]
@maries24 No strict timeline sorry, but I'll try and look at this as soon as I can.

**Comment by engram-design** [comment]
Thanks to [mattstein](https://github.com/verbb/comments/pull/227), this has been implemented in [1.8.7](https://github.com/verbb/comments/releases/tag/1.8.7)

**Comment by maries24** [comment]
Massive thank you @engram-design and @mattstein !
