### ISSUE TITLE
When delete a Product, the Comment Dashboard Widget throws an Error

### ISSUE THREAD

**Issue by francoislevesque** [verbb/comments#219]
**Description**

When deleting a Product having comments, the Comment Dashboard Widget throws an Error: 
craft\services\Elements::getElementById() must be of the type int, null given.

**Steps to reproduce**
1. Create a product (or an entry)
2. Add a comment
3. Delete the product
4. Show the comment widget on the dashboard
5. Error!

**Additional info**
- Plugin version: 1.8.4
- Craft version: 3.5.18
- Multi-site: Yes

**Additional context**

```
// /verbb/comments/src/elements/Comment.php

if ($cacheKey && $this->_owner = $renderCache->getElement($cacheKey)) {
  return $this->_owner;
}

// ⚠ This line seems to be problematic!
$this->_owner = Craft::$app->getElements()->getElementById($this->ownerId, null, $this->siteId);
      
if ($this->_owner) {
  $renderCache->addElement($cacheKey, $this->_owner);
}

```

**Comment by engram-design** [comment]
Should be fixed in [1.8.5](https://github.com/verbb/comments/releases/tag/1.8.5)
