### ISSUE TITLE
Page crashes when viewing comment from a deleted user in CP

### ISSUE THREAD

**Issue by tamlyn** [verbb/comments#220]
**Description**

```
Twig\Error\RuntimeError: Impossible to access an attribute ("cpEditUrl") on a null variable. 
in /app/vendor/verbb/comments/src/templates/comments/_edit.html:134
```

**Steps to reproduce**
1. Create a user
2. Add a comment as that user
3. Delete that user
4. The comment is shown in the control panel comment view as being by `[Deleted User]`
   ![image](https://user-images.githubusercontent.com/115310/112028043-ae5d3580-8b2f-11eb-875e-dd88de98f154.png)
5. Click to view the comment
6. 💥 

**Additional info**
- Plugin version: 1.8.5
- Craft version: 3.6.10
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Fixed in [1.8.6](https://github.com/verbb/comments/releases/tag/1.8.6)
