### ISSUE TITLE
Translation key "under review" cannot be translated

### ISSUE THREAD

**Issue by pejeio** [verbb/comments#221]
**Description**
Translation key` Your comment has been posted and is under review.` cannot be translated.
It fallbacks to the English translation. All other fields work perfectly ('Your name', 'your email',...).

### Steps to reproduce
1. Create 2 folders in the project’s translations directory:
* nl
* en
2. For the NL directory, create this **comments.php** file:
```
<?php

return [
    'Your name' => 'Naam',
    'Your email' => 'E-mailadres',
    'Add a comment...' => 'Schijf een reactie...',
    'Your comment has been posted and is under review.' => 'Je reactie wordt nu gecontroleerd.',
];
```
3. For the EN directory, create this **comments.php** file:
```
<?php

return [
    'Your name' => 'Name',
    'Your email' => 'Email (will not be published)',
    'Add a comment...' => 'Write a comment',
    'Your comment has been posted and is under review.' => 'Testing',
];
```
4. Submit a form on the NL site.

### Actual behavior
You will see _Testing_ instead of _Je reactie wordt nu gecontroleerd._ on the NL site.

**Additional info**
- Plugin version: 1.8.5
- Craft version: 3.6.11.1
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed in [1.8.6](https://github.com/verbb/comments/releases/tag/1.8.6)
