### ISSUE TITLE
Comments JS does not instantiate when routing static assets through Cloudflare

### ISSUE THREAD

**Issue by jsmrtn** [verbb/comments#222]
When using Cloudflare, the JS does not instantiate correctly, as Cloudflare uses Rocket Loader to defer loading of the JS until the page renders. Apparently, whatever Rocket Loader is doing doesn't play well with the comments JS:
````
VM28:80 Uncaught ReferenceError: Comments is not defined
    at <anonymous>:80:47
    at c (rocket-loader.min.js:1)
    at l (rocket-loader.min.js:1)
    at t.simulateStateAfterDeferScriptsActivation (rocket-loader.min.js:1)
    at Object.callback (rocket-loader.min.js:1)
    at t.run (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at HTMLScriptElement.<anonymous> (rocket-loader.min.js:1)
````
<img width="535" alt="Screenshot 2021-04-14 at 11 14 56" src="https://user-images.githubusercontent.com/1694957/114695150-2f64b280-9d13-11eb-8c4f-956705877016.png">

**Comment by jsmrtn** [comment]
There's [two fixes available from Cloudflare](https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-specific-JavaScripts-), but unfortunately neither of them appear to be suitable. It doesn't look like you can add the tag to the script output directly, and the page rule (as far as I can see) still loads Rocket Loader even if you have requested it not to. I've disabled Rocket Loader entirely (as for us the gains were marginal), but that may require more planning dependent on your circumstances.

<img width="1046" alt="Screenshot 2021-04-14 at 11 35 48" src="https://user-images.githubusercontent.com/1694957/114697505-e6622d80-9d15-11eb-92d1-82d918a65e52.png">

**Comment by engram-design** [comment]
Did you mean to close this?

**Comment by jsmrtn** [comment]
@engram-design Yeah it was more of a 'wiki' entry I suppose, in case someone else comes up against this in future–they can search the issues and find the answer.

**Comment by engram-design** [comment]
Cool, I'll take a look into it further

**Comment by peteeveleigh** [comment]
Was any workaround found for this which didn't involve disabling RocketLoader?

**Comment by peteeveleigh** [comment]
I got around this issue by rendering the plugin JS within the template using https://verbb.io/craft-plugins/comments/docs/template-guides/available-variables#craft-comments-renderJs
