### ISSUE TITLE
Upgrading sets all comment dateUpdate values to current time of upgrade

### ISSUE THREAD

**Issue by accalton** [verbb/comments#224]
We recently upgraded Comments from version 0.4.9 on a Craft 2 site to the current version, 1.8.6, and noticed that the dateUpdated column in the craft_comments_comments table was set to the same time which was the current time of the upgrade being run.

**Steps to reproduce**
1. Have Comments v0.4.9 installed on Craft 2
2. Use Composer to require verbb/comments
3. Run the required migration

**Additional info**
- Plugin version: 0.4.9 to 1.8.6
- Craft version: 3.6.7
- Multi-site: No

**Comment by engram-design** [comment]
This is largely unavoidable at the moment, as via the migration process, each comment is re-saved, thus altering their updated time.
