### ISSUE TITLE
Issue with showCustomFields having been removed

### ISSUE THREAD

**Issue by rowansentesy** [verbb/comments#229]
**Description**
I updated to the latest version of the add-on today while troubleshooting another issue.
I am getting an error 
```Calling unknown method: verbb\comments\models\Settings::showCustomFields()```

I'm not sure if this is a documentation error, or if the showCustomFields settings should be replaced? 

thanks!

**Steps to reproduce**
1. Use provided template with code block:
```
{% for field in fieldLayout.getFields() %}
...
{% endif %}
```
2. Open page with comment form provided in examples: https://github.com/verbb/comments/blob/craft-3/examples/html/form.html

**Additional info**
- Plugin version: 1.8.7
- Craft version: 3.6.16
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Are you using the config file `comments.php` to set the plugin settings, or are you just using the control panel?

This setting was indeed recently removed, and it _should_ be unsetting that setting if you have got it set in your plugin settings https://github.com/verbb/comments/blob/craft-3/src/Comments.php#L402

I'll look into it now

**Comment by engram-design** [comment]
Just realised the example HTML and some areas of the docs were still referring to `showCustomFields`, so updated that.

Let me know if it's still an issue!
