### ISSUE TITLE
Documentation issue: Spam Guard - unsupported?

### ISSUE THREAD

**Issue by rowansentesy** [verbb/comments#238]
**Description**
I started having a look at the documentation found here with regards to 'Spam Guard' installation 
https://verbb.io/craft-plugins/comments/docs/feature-tour/anti-spam

I tried to install it, but realized that the plugin is 7 years old and apparently has no support for Craft 3. 

Is there a suitable replacement for Spam Guard that is supported and that you can recommend? 
I suggest you update your docs to remove that suggestion for others in the future.

If by chance there is a way to install this and it is compatible, please let me know how I can go about doing that. 

Craft v 3.7.1
Comments v dev-craft-3 as 1.8.7

Regards,
Rowan

**Comment by engram-design** [comment]
Good point, forgot that was in there from the Craft 2 days. May very well need to add support for [snaptcha](https://plugins.craftcms.com/snaptcha) which seems to be the best bet these days.

**Comment by rowansentesy** [comment]
Thanks for letting me know.
Do you have any instructions for how to add snaptcha to Comments at the moment? Or, would you recommend I wait until you officially roll it into a future release?

thanks!

**Comment by engram-design** [comment]
I can't say I'm actually familiar with snaptcha (yet), but from what I've read it's compatible with most forms, you just might need to add some HTML inputs to the comment form (which would be what our official support would be).

However most of the stuff in snaptcha is covered by our own core spam protection, so depends if you really need it. reCAPTCHA has also proven to be the best overall performer out of any approach.
