### ISSUE TITLE
Change all email notifications to be routed through the queue

### ISSUE THREAD

**Issue by engram-design** [verbb/comments#240]

**Comment by nicolasbottari** [comment]
Any possible ETA for this feature? I have a client whose comments trigger hundreds of emails to be sent, and they're reporting that the sending is quite slow. A background process for emailing would resolve this.

I'd work around this for now through an event hook if necessary/possible, but I do feel this should be a native feature of the plugin. Thanks!

**Comment by nicolasbottari** [comment]
In face, this is going to become a problem as I'm seeing users re-pressing the "submit" button multiple times, thinking it didn't go through the first time, when the form submission was likely churning though hundreds of emails being sent.

**Comment by engram-design** [comment]
No strict ETA sorry, and understand there's performance implications on this. Will do my best to schedule this in for the next few releases.

**Comment by engram-design** [comment]
Added in [1.9.2](https://github.com/verbb/comments/releases/tag/1.9.2), but disabled by default for a non-breaking change.
