### ISSUE TITLE
GraphQL: expose author id on CommentInterface

### ISSUE THREAD

**Issue by bzin** [verbb/comments#260]
### What are you trying to do?

I am trying to mark an author of an entry to on a comment. If the comment would has a `userId` property I could mark this comment has author since he was the one that created the `Element` of the entry I am reading.

### What's your proposed solution?

Make a `userId` available in the `CommentInterface` so if a Craft user created an entry and added a comment we could validate this has the comment `author`.

**Comment by engram-design** [comment]
We already have [`userId`](https://github.com/verbb/comments/blob/1083e35d38550cffe6185f4737ba890b9adde25f/src/gql/interfaces/CommentInterface.php#L122) exposed in the `CommentInterface`, so it might be a permissions thing?

**Comment by bzin** [comment]
This was indeed a permissions thing. Thanks @engram-design
