### ISSUE TITLE
User photo will not render

### ISSUE THREAD

**Issue by mitchellgemma** [verbb/comments#261]
### Question

Are there any config settings that need to be set in order to user photos to render properly? Is there anything else that would cause a user photo's to be incorrect?

### Additional context

When calling `{{ craft.comments.render(entry.id) }}` and using the default template, the photos for users do not render properly. In the src for the photo, it only says the file name, and does not include the path to the file. Also, when trying to select a default user photo in the Craft admin panel, no existing pictures load and I am told a server error has occured.

**Comment by engram-design** [comment]
Shouldn't be anything special, but what Comments and Craft versions are you on? This should probably have been filed as a bug issue to get that info from you.

What are the settings for your Volume (and Filesystem if using Craft 4) that's configured as the "User Photo Location"?

**Comment by mitchellgemma** [comment]
Good morning! Here are the settings I am using. 
<img width="1663" alt="Screen Shot 2022-09-22 at 9 52 56 AM" src="https://user-images.githubusercontent.com/107566585/191765734-8fdeebdf-db84-4fea-b0bf-f731a1415944.png">

**Comment by mitchellgemma** [comment]
I'm also using Craft version 4.2.5.1 and comments version 2.0.2.1
