### ISSUE TITLE
Count the number of comments on an entry?

### ISSUE THREAD

**Issue by mitchellgemma** [verbb/comments#262]
### Question

Is it possible to count the number of comments on an entry?  I have a channel with entries, and have comments enabled for each entry. I am just trying to get a number for the total comments on a single entry. Nested replies are disabled, so it is only 1 level of comments. Thanks!

**Comment by lucosius** [comment]
This one should help:

```
 {% set params = {
    ownerId: entry.id
} %}
{{ craft.comments.fetch(params) | length }}
```

**Comment by mitchellgemma** [comment]
That did the trick, thank you!

**Comment by engram-design** [comment]
Word of warning that you should use `{{ craft.comments.fetch(params).all() | length }}` or `{{ craft.comments.fetch(params).count() }}` as without these functions, you're getting the length of the `CommentQuery`, which will give you unexpected results.
