### ISSUE TITLE
CSS missing on /admin/comments/settings?site=default

### ISSUE THREAD

**Issue by yingban** [verbb/comments#267]
### Describe the bug

Hi,

I just updated to the 2.0.3.
It seems that a CSS file is not loaded on the view.

### Steps to reproduce

1. Update the plugin to 2.0.3
2. Go to admin/comments/settings?site=default

### Craft CMS version

4.2.7

### Plugin version

2.0.3

### Multi-site?

No

**Comment by engram-design** [comment]
Not sure what you mean, sorry? There's only `comments-cp.css` loaded on that page, although there's really no usage of custom CSS for the settings of the plugin. Or do you mean _all_ CSS is missing?

**Comment by yingban** [comment]
Sorry for not being enough clear.
Yes, all CSS.

Anybody else has the same behaviour?

**Comment by engram-design** [comment]
Can't replicate that I'm afraid! Have you cleared your Craft caches (under Utilities)?

**Comment by yingban** [comment]
@engram-design 
Deeply sorry, found the issue in my comments.php.

I have a custom function which set "requireModeration" to true or false depending of user group or the current user.
Yesterday before updating Craft CMS and Comments, it was working like a charm.
