### ISSUE TITLE
Comment detail page not accessible

### ISSUE THREAD

**Issue by dowadidi** [verbb/comments#275]
### Describe the bug

In the CP, when clicking on a comment, you get an 404 Comment not found message.

### Steps to reproduce

1. Create a comment in the frontend.
2. Try to edit/moderate it in the backend by clicking on it.

### Craft CMS version

4.2.8

### Plugin version

2.0.5

### Multi-site?

Yes

### Additional context

The comments are listed properly. This happens both local and on the staging server. Both using PHP 8.1. And for all sites in the multi-site setup, even if using main-site.tld/admin or secondary-site.tld/admin.

The error is thrown on this line: https://github.com/verbb/comments/blob/craft-4/src/controllers/CommentsController.php#L81

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, change your `verbb/comments` requirement in `composer.json` to:

```
"require": {
  "verbb/comments": "dev-craft-4 as 2.0.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by dowadidi** [comment]
That was quick! And can confirm the issue is fixed!
