### ISSUE TITLE
GraphQL - upvoting a comment is stored as downvoting

### ISSUE THREAD

**Issue by bzin** [verbb/comments#278]
### Describe the bug

Working with Craft in `headless` mode and, when trying to use `upvote` as described in [documentation](https://verbb.io/craft-plugins/comments/docs/developers/graphql#voteComment), the comment receives an `downvote` instead.

Also other errors shown regarding the requested data:
![CleanShot 2023-02-22 at 14 58 13](https://user-images.githubusercontent.com/382735/220641740-bb605cda-046c-4533-ae00-e8e34b7590d7.png)

PS: the `downvote` does indeed set a `downvote`.

### Steps to reproduce

1. Having comments, vote and flagging to not allow guest posts
2. Login/Impersonate a user login (we use Craft cookie session and CSRF when communicate with graphql endpoint)
3. Execute mutation query `voteComment ` as described in docs 

### Craft CMS version

4.3.6.1

### Plugin version

2.0.6

### Multi-site?

No

### Additional context

We are using this in a `headless` craft installation. We use Craft cookies to keep a login session in the frontend. The frontend is with React / Next.js.

**Comment by engram-design** [comment]
So to be fair, someone did PR the GQL mutations functionality and wrote the docs (Matt Stein from P&T), so I probably didn't check it as thoroughly as I should've. So firstly, the docs are incorrect - refer to the [updated page](https://verbb.io/craft-plugins/comments/docs/developers/graphql#voteComment).

There was also an issue with the return type for these mutations. Fixed for the next release. To get this early run `composer require verbb/comments:"dev-craft-4 as 2.0.6"`

**Comment by bzin** [comment]
Great, I will have a look at it @engram-design and will let you know here.

**Comment by bzin** [comment]
Hi @engram-design , the version you mentioned and the documentation you shared is working nicely.

Thanks for the great work!
