### ISSUE TITLE
Omit moderator's comments from requiring moderation

### ISSUE THREAD

**Issue by peteeveleigh** [verbb/comments#292]
### Question

This is a two-fold question. Both are related.

Basically we have a situation where users can leave comments/reviews which require moderation. But we also have the ability for people to leave replies on the comments. These replies are generally the site owner answering a question or saying thank you. Since it isn't easy to do this from the Control Panel, the site owner is using the front end

**Question 1.** Is it possible to configure the plugin so members of the moderator user group (as set in the plugin settings) don't require their comments to be moderated? We are finding that when members of the moderators group reply to a comment on the front end, their reply requires moderation. So they then need to go and find their reply in the CP and approve it.

**Question 2.** Is there a way to reply directly to a comment from within the CP? (If not then a "New reply" button on the CP Comment form might be a nice feature request.

**Comment by engram-design** [comment]
We'll need to add some exclusion groups to the moderation setting for this to work.

I'll add creating comments via the CP on our todo list.

**Comment by aarmitage** [comment]
+1 for both of these please!

**Comment by engram-design** [comment]
Added a moderator exclusion setting for the next release. To get this early run `composer require verbb/comments:"dev-craft-4 as 2.0.9"`

**Comment by aarmitage** [comment]
Thank you for making this update. Do you know when this dev version will be pushed to 2.0.10 (or equivalent)?

**Comment by engram-design** [comment]
Update in [2.0.10](https://github.com/verbb/comments/releases/tag/2.0.10)
