### ISSUE TITLE
Unable to find the template in "_includes/avatar"

### ISSUE THREAD

**Issue by vonscriptor** [verbb/comments#297]
### Describe the bug

I'm trying to `{% include '_/partials/example' %}` from inside `_comments/_includes/avatar.twig` and get the following error:
`Unable to find the template “_/partials/example” in "_includes/avatar" at line 20.`

### Steps to reproduce

1. Use Custom Templates
2. Try to include a template that lives outside the `templateFolderOverride` location

### Craft CMS version

4.8.2

### Plugin version

2.0.11

### Multi-site?

No

**Comment by engram-design** [comment]
So yes, it's going to try and find that template relative to `_comments`, because that acts as the template root.

Using the `commentsSiteInclude()` Twig function should work to resolve that, and is identical to the `include` tag.

```twig
{{ commentsSiteInclude('_/partials/example') }}
```

**Comment by vonscriptor** [comment]
Perfect, that worked. I didn't see that mentioned in the docs, so might be nice to add! 😁 Thanks!
