### ISSUE TITLE
Commenters' submitted text strips punctuation

### ISSUE THREAD

**Issue by smartpill** [verbb/comments#298]
### Describe the bug

When a commenter types or pastes text with quotes or dashes, etc. in the submitted comment, the characters are stripped out and don't appear in the CP. So posted comment is missing punctuation.

### Steps to reproduce

1.  Log in
2. Submit comment with quotes or dash, n-dash or m-dash in text

### Craft CMS version

4.5.11

### Plugin version

2.0.8

### Multi-site?

Yes

**Comment by engram-design** [comment]
Can you update to [2.0.11](https://github.com/verbb/comments/blob/craft-4/CHANGELOG.md#2011---2024-03-04) as this should already be fixed?

**Comment by smartpill** [comment]
Thanks, I think that worked. No complaints so far.

**Comment by smartpill** [comment]
Thanks, I think that worked. No complaints so far.
