### ISSUE TITLE
FR: Add extra fields

### ISSUE THREAD

**Issue by alecritson** [verbb/comments#32]
This might be out of the scope of this plugin, but thought i'd request it.

It would be cool to be able to have extra fields with comments, for example if you wanted to give a star rating with your comment, you could have a field ready to go for it.

Awesome plugin though :)

**Comment by engram-design** [comment]
Really glad you like it! It's got a little bit more refinement to go, and a bucket of features to include :smiley: 

Totally agree, its something I've touched on in the roadmap `Support field layouts to allow full customisation over comment form.` which I'm picturing would give you full control over the form - obviously with the comment field being compulsory.

**Comment by JonnyTurnerUK** [comment]
Sorry to just onto an old thread guys, but is this still in the pipeline?

**Comment by engram-design** [comment]
Its taken a good while, but [1.3.1](https://github.com/verbb/comments/releases/tag/1.3.1) adds support for custom fields on comments.
