### ISSUE TITLE
Import CSV

### ISSUE THREAD

**Issue by Mr-Chilly** [verbb/comments#43]
Hi, great plugin!

Is there anyway to import a csv (say, take from wordpress) into the plugin? I've used craft import (https://github.com/boboldehampsink/import) however it doesn't seem to have an option link into the comments plugin

Thanks

**Comment by engram-design** [comment]
Not currently, but keep an eye on [Feed Me 2.0](https://github.com/engram-design/FeedMe/tree/2.0.0) which will support JSON/XML importing for custom element types.

**Comment by DrChills** [comment]
Awesome! Will look foward to it -, and again, thanks for the great work...

**Comment by ykimura32** [comment]
Any updates on this feature?  Could really use it about now.  Thanks!

**Comment by engram-design** [comment]
Comments support had been added to Feed Me [3.0.0-beta.23](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.23) for Craft 3.
