### ISSUE TITLE
Comments are being submitted twice

### ISSUE THREAD

**Issue by subratom** [verbb/comments#49]
I am using the ajax sample from your code and it throws exception for params. So I had to remove it (not sure what params need to be passed).

When I removed it, and tested the plugin, I notice that the comments are being submitted twice, also I can't click on edit/ delete. As I try, dropdown that has the options of edit/ delete disappear. Any idea?

Also I can't seem to be able to reply to existing comments.

**Comment by engram-design** [comment]
Sure, the example templates were just missing the optional `params` variable. Feel free to remove that if you don't need it, but have updated the examples.

Are you getting any JS errors on page load, or when trying to submit/edit/delete a comment?
