### ISSUE TITLE
On save template returns '1'

### ISSUE THREAD

**Issue by hatzipanis** [verbb/comments#57]
Whenever I submit or save a comment, both on the front-end and the back-end, the comment saves but the template displays nothing but the character `1`.

I've looked around but can't find anything about such an issue and therefore tend to think it may be my template. Any help appreciated.

**Comment by engram-design** [comment]
When you say saving on the back-end, you mean going to your CP > Comments, selecting a comment and hitting "Save comment" produces a `1` character? Certainly doesn't do that for me, but that wouldn't really point to a template issue.

For the front-end, are you using any of the example code? Ajax or non-Ajax?

**Comment by hatzipanis** [comment]
Ok, problem solved by disabling [comments-rating](https://github.com/madebyshape/comments-rating).

It actually saved fine in the back-end when using 'Set Status' from the all comments view. But if I click into a comment and tried to save it there it would return a `1`.

[comments-rating](https://github.com/madebyshape/comments-rating) didn't work for me also so I'll create an issue over there and see if they can look into it.

Thank you for your quick response!

**Comment by engram-design** [comment]
Ah, I see. Might be something in the hooks they're using - but please refer back to this issue if its indeed an issue with Comments. Have to say, have yet to give the ratings plugin a real test-drive, but can if need be!

**Comment by madebyshape** [comment]
Whoops - Looking in to this issue today, will post back on here once I've found a fix for it.
