### ISSUE TITLE
onTrashComment not firing

### ISSUE THREAD

**Issue by madebyshape** [verbb/comments#58]
I've got an `onTrashComment` event inside my plugin but it doesn't seem to be firing when the status of a comment is set to Trash :(

Is there something I'm missing?

```
craft()->on('comments.onTrashComment', function($event) {
    $comment = $event->params['comment'];
    CommentsRatingPlugin::log('Trashed');
    craft()->commentsRating->trashRating($comment);
});
```

**Comment by engram-design** [comment]
Just tested this locally, and is working fine for me? This won't be triggered through the CP's element status change, so that might be where things are tripping up?

**Comment by madebyshape** [comment]
Yeah possibly. I'm changing the status in the CP for Comments to 'Trashed' but it doesn't do it. How do comments get trashed other than in the CP?

**Comment by engram-design** [comment]
Sure, there's a direct controller action for the front-end side of things, but makes sense to trigger this also from the CP. If you wouldn't mind giving the latest master a go, that should trigger properly now (when saving a comment via the CP, or when using the element actions).
