### ISSUE TITLE
Vote change as often as you like

### ISSUE THREAD

**Issue by EternalBlack** [verbb/comments#59]
I would prefer to be able to "change my mind" at any given time. Currently when I upvote a comment, I can't downvote the same comment again after that and vice versa. 
`Comments_CommentModel.php` line `254` i.e. line `260` are the ones currently keeping me from that. (Actually I commented out the `if-block`, still doesn't work).
Also, is there any way to get the overall "Points" a user received? i.e. something like `user XYZ has 5 comments and a total of -1231 points`?

**Comment by engram-design** [comment]
This has been fixed and overall addressed in Comments 1.0+ for Craft 3.

**Comment by yingban** [comment]
Hi @engram-design 

when I downvote a comment and change my mind right after, and click twice on the up direction chevron, i got an error message but my choice is sometimes registered and I have an error message saying that I already voted.

Is that normal?

**Comment by engram-design** [comment]
Should be fixed in [2.0.3](https://github.com/verbb/comments/releases/tag/2.0.3)
