### ISSUE TITLE
Internal Server Error?

### ISSUE THREAD

**Issue by alexlabarces** [verbb/comments#61]
Hello,

It seems that a 500 error is being thrown for any user other than the first one created when accessing the comments listing page. The comments listing page works fine for the first user with the same privileges, but not for other users in the system. The other sections of the plugin can be accessed (settings, permissions) through their direct URL, but not the main listing page (All Comments).

Updated to the latest version of the plugin (0.4.7) in hopes that it would solve this issue, but it persists. Any help in figuring this one out would be much appreciated as comment management is key for the website in question.

Thank you!

**Comment by engram-design** [comment]
@alexlabarces I can't seem to replicate this with a number of different use cases (a new Admin user, and a regular User). Do you have devMode on for any further additional information to debug?

Otherwise, I'd probably need to see either a database dump or a staging server to have a look at what might be going on...

**Comment by theskyfloor** [comment]
I'm getting this error on my dev site. Any thoughts? I am using social login for most of the user accounts if that matters? I can't a comment to work besides my admin user : (

**Comment by engram-design** [comment]
@theskyfloor Craft 2 or Craft 3?

**Comment by theskyfloor** [comment]
3. Hoping to show to the client tomorrow, sorry for the last minute question just got around to testing all the way. I can give you access if you need it.

**Comment by engram-design** [comment]
@theskyfloor For clarity, this was caused by misconfigured email settings on the server causing a timeout. Disabling email notifications works, or setting up Craft's emails.
