### ISSUE TITLE
No JSON response when validation fails during AJAX submission?

### ISSUE THREAD

**Issue by jaytdev** [verbb/comments#62]
When submitting the form through AJAX, the server response is a 404 if the validation fails. There isn't a JSON response returned in that context.

The expectation seems to be a full page reload in the event of an error. You would then use the activeComment variable to display the errors.

This isn't necessarily something anyone should be running into very often because we should be validating the form on the front-end before submission, but I think it would be a good idea to check the request type (AJAX or otherwise) regardless of validation in order to respond with the expected return type.

A JSON response with the validation errors would be very useful in this context.

Is there already a way of handling this? Maybe I've overlooked something :)

**Comment by engram-design** [comment]
The templating side of things has been given a big overhaul in Comments 1.0+ for Craft 3, so going to mark this one as closed to focus efforts there.
