### ISSUE TITLE
Incorrect comment counts when deleting user account

### ISSUE THREAD

**Issue by fyrebase** [verbb/comments#64]
Fantastic plugin Crawf, I'm really liking what you have created here.

I've noticed when deleting a user account the comment counts become inaccurate. What do you think about the idea of preserving the comments from a deleted account or maybe replacing theme with a custom message?

The easiest thing to do at the moment for myself is to remove the cascade on delete for the `UserRecord` but I'm not sure what implications that might have down the road.

**Comment by engram-design** [comment]
Gotcha, this has been improved in Comments 1.0+ for Craft 3. Comments made by a user that's been deleted will be turned to 'Anonymous', as we're relying on the user account information to identify the name of the user, etc.
