### ISSUE TITLE
Add getTotalApprovedComments method or add status argument to getTotalComments method

### ISSUE THREAD

**Issue by fyrebase** [verbb/comments#65]
It would be nice to be able to get the total approved comments for use in front end templates.

I would suggest creating a specific method `getTotalApprovedComments` or add an status argument to the `getTotalComments` method within the `CommentsService.php`.

Happy to provide a pull request depending on which route is appropriate.

**Comment by engram-design** [comment]
Total for just an element? You should be able to use `{{ craft.comments.all({ elementId: entry.id, status: 'approved' }) | length }}` (for Craft 2)?
