### ISSUE TITLE
Reply comment count may be inaccurate within frontend templates 

### ISSUE THREAD

**Issue by fyrebase** [verbb/comments#66]
When using `<a class="comment-toggle">{{ comment.descendants | length }} comments</a>` within the front end templates is it providing a count for all replies regardless of status.

It may not always be the desired result to count all comments. In my case I only wanted to count all approved comments. An easy fix is to filter the descendants:

    <a class="comment-toggle">{{ comment.descendants.status('approved') | length }} comments</a>

**Comment by engram-design** [comment]
Good call. This should be fixed in Comments 1.0+ for Craft 3, where by default only approved comments are returned.
