### ISSUE TITLE
No comment on comment

### ISSUE THREAD

**Issue by PopaWeb** [verbb/comments#74]
I see the main comment. The comment on other user are not showing. I see  the comment count but when i click on it, nothing append. When i lokk in the html code, they are not there either. I am using the default templates.

**Comment by Maarco73** [comment]
I have the same problem. I see only the number of comments but no replies to the comments. I'm using the default templates, too. I testet it with ajax & standard example.

**Comment by matthew-gibbs** [comment]
I also have this problem - do we have anyone who knows of a fix?

**Comment by Maarco73** [comment]
I got a solution for this - i took an older version of this file:
https://github.com/engram-design/Comments/blob/b05fd384bfbc9caed5f69df4dc72da991fef9c47/comments/templates/_forms/templates/comment.html

**Comment by engram-design** [comment]
Closing to focus efforts on templates in Comments 1.0+ for Craft 3.
