### ISSUE TITLE
Out of memory when viewing comments in control panel

### ISSUE THREAD

**Issue by bkmorse** [verbb/comments#76]
Plugin version 0.4.4
Craft CMS 2.6.2983
PHP 7.0 (LAMP stack)

When going to project.dev/admin/comments in the control panel, it times out and gives me an error saying it ran out of memory.

> Fatal error: Out of memory (allocated 268435456) (tried to allocate 20480 bytes) in craft/app/models/BaseModel.php on line 266
> 
> Fatal error: Out of memory (allocated 268435456) (tried to allocate 167936 bytes) in craft/app/etc/logging/FileLogRoute.php on line 65

This is happening on a server that has 2 gigs of ram dedicated to it.

There are currently 89880 comments in the database, a lot I know, but I tried to modify the template that displays the comments in the control panel to paginate the comments but the way it is setup is over my head. Can there be some eager loading or pagination implemented in the case of a craft build with a large amount of comments?

**Comment by bkmorse** [comment]
80k+ comments and the control panel for viewing comments is unusable.

**Comment by engram-design** [comment]
Thanks for this - we haven't done performance testing of this sort of scale, but the CP should at least paginate items, and unless you have a significant amount of comments on a single element, I wouldn't have thought this would be an issue.

Happy to investigate, but priority will be Comments 1.0+ for Craft 3.
