### ISSUE TITLE
Plans for Craft 3 support?

### ISSUE THREAD

**Issue by StevenLangbroek** [verbb/comments#77]
Hey! I was wondering if you had already started working on Craft 3 support?

**Comment by engram-design** [comment]
Work has already begun on Craft 3 actually - you might be wondering why its been a little quiet around here!

We'll have some updates in the next few weeks.

**Comment by EmptyStreets** [comment]
Please add stars/rating functionality.

**Comment by degraaf** [comment]
Looking forward to having this available on Craft 3!

**Comment by engram-design** [comment]
Comments 1.0+ for Craft 3 is out now!
