### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by bymayo** [verbb/comments#80]
Is there anyway to enable 'Emojis' in the comments?

**Comment by bymayo** [comment]
My bad - They do actually work! So not sure why they wouldn't show up before!

**Comment by engram-design** [comment]
I wonder if this is related to https://github.com/craftcms/cms/issues/1627 and https://craftcms.stackexchange.com/questions/17277/mysql-collation-utf8mb4-unicode-ci-emojis ?
