### ISSUE TITLE
Clean up Comments structure on uninstall

### ISSUE THREAD

**Issue by michaelrog** [verbb/comments#82]
### Description

The plugin should clean up its structure before uninstall.

(Currently, it leaves an orphan entry in the `craft_structures` table.)

### Steps to reproduce

1. Install the plugin. (A new structure is created in the `craft_structures` table.)
2. Uninstall the plugin. (The structure is not removed.)

### Additional info

- Plugin version: 0.4.9

**Comment by engram-design** [comment]
Agreed, and this has been rolled into Comments 1.0+ for Craft 3.
