### ISSUE TITLE
CommentRecords should track their associated ElementRecords as a foreign key

### ISSUE THREAD

**Issue by michaelrog** [verbb/comments#83]
### Description

CommentRecords should track their associated ElementRecords as a foreign key. Currently, when a comment is deleted, its entry from `craft_elements` is removed — because `CommentsService:deleteComment()` uses `ElementsService:deleteElementById()` — but its row in `craft_comments` is left behind orphaned.

### Additional info

- Plugin version: 0.4.9

**Comment by engram-design** [comment]
@michaelrog Thanks for this, and this has been rolled into Comments 1.0+ for Craft 3.
