### ISSUE TITLE
Unable to disable email notifications

### ISSUE THREAD

**Issue by ghost** [verbb/comments#85]
### Description

Like the title says, email notifications keep coming regardless of being disabled

### Steps to reproduce

1. Go to plugin settings
2. Disable "Enable Author Notifications" and "Enable Reply Notifications"

### Additional info

- Plugin version: 0.4.7
- Craft version: 2.6.2999

Edit: Is there somewhere in the plugin code I can comment out this functionality altogether, just as a hacky way to make it stop?

**Comment by engram-design** [comment]
This should be fixed in Comments 1.0+ (for Craft 3), as the Craft 2 version is likely to get no further updates.

If you'd like to hack this yourself, its in https://github.com/verbb/comments/blob/craft-2/comments/services/CommentsService.php#L136-L144
