### ISSUE TITLE
Column 'dateCreated' in order clause is ambiguous

### ISSUE THREAD

**Issue by bymayo** [verbb/comments#88]
### Description

After updating to the latest version fo Comments, and then submitting a comment I get this error:

```
Internal Server Error
CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'dateCreated' in order clause is ambiguous
```

Is this a similar issue to what happened with the Craft 3 version? https://github.com/verbb/comments/commit/fa7ed66fa36e9d59eb70f01b75ac62fd2234df5f

### Additional info

- Plugin version: 0.5.0
- Craft version: 2.7.2

**Comment by engram-design** [comment]
Quite possibly a similar issue, I'll look into fixing this, but we're prioritising Craft 3 fixes/improvements in the short term.

**Comment by bymayo** [comment]
@engram-design Is there anyway we can push this a little bit? Because we've got a site currently using the latest version of Craft, with broken Comments 😭Hit me up on Slack to discuss (@bymayo).

**Comment by engram-design** [comment]
For reference, I believe this is simply a error in our docs, so sorry about this. Change your template call to:

```
{% set params = {
    order: 'commentDate asc',
} %}
```
or
```
{% set params = {
    order: 'elements.dateCreated asc',
} %}
```
