### ISSUE TITLE
Feature request: send out a notification for flagged comments

### ISSUE THREAD

**Issue by arifje** [verbb/comments#94]
Comment flagging is great, but mainly meant for website owners and staff to get a clear picture about inappropriate comments on their website. Currently no notifications are sent out to the admins if a comment is flagged. Also, the only place to find out which comments are flagged is the front end. 

To make this a better feature it would be really nice to have a option to send out a notification when a comment is flagged, but also that we could see them (and sort/order) in the CP.

**Comment by engram-design** [comment]
Added in [1.8.0](https://github.com/verbb/comments/releases/tag/1.8.0)
