### ISSUE TITLE
Can't delete

### ISSUE THREAD

**Issue by rtrudel** [verbb/comments#95]
### Description
Impossible to delete comment as Exception class is not found

### Steps to reproduce

1. Comment
2. Delete comment
3. Get this error

![image](https://user-images.githubusercontent.com/18495095/46449710-8c06b000-c75b-11e8-9457-793fe1d5f367.png)

### Additional info
I am using the comment plugin on a multi-site environnement (on the secondary site)

- Plugin version: 1.0.2
- Craft version: 3.0.26.1

**Comment by rtrudel** [comment]
This is related to #96 . Bug only happens using Comments in another site than the primary one.

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/comments/releases/tag/1.0.3)
