### ISSUE TITLE
Multisite installation seems not supported

### ISSUE THREAD

**Issue by rtrudel** [verbb/comments#96]
### Description
When using the comment plugin on a site which is not the primary site, when you send a comment, it saves in the primary site anyway, that means no comment are shown in the secondary site.

I explain: my primary site is my landing page, my secondary site is my member-only area where I have a forum-like section using comments.

I have to force the "siteId" in the criteria, but unfortunately it's required to use sitedId:1 even on the secondary site in order to be abe to both post and read comments.

### Steps to reproduce

1. Install the comment section in the template of a secondary site using 
`{{ craft.comments.render(entry.id) }}`
2. Post a comment
3.  Refresh the page = no comments
4. Go in CP in the Comments
5. Select primary site: comment is there
6. Switch to secondary site in the combobox on top = no comments

ALTERNATIVE

1. Install the comment section in the template of a secondary site using 
`{{ craft.comments.render(entry.id, {siteId: 2}) }}`
2. Post a comment
3. Comment goes in primary site anyway
4. Refresh = no comment (as comment is saved in primary site...)

ALMOST WORKING ALTERNATIVE

1. Install the comment section in the template of a secondary site using 
`{{ craft.comments.render(entry.id, {siteId: 1}) }}`
2. Post a comment
3. It works but the comment is on primary site anyway, which is kinda workaround but not the proper way to store the data. 

### Additional info
Maybe related, imposible to delete a comment using the last of the three procedure above. I opened another issue for this, it's maybe not related. 

- Plugin version: 1.0.2
- Craft version: 3.0.26.1

**Comment by rtrudel** [comment]
Note that I worked around this by swapping my primary and secondary site in the CP.  I also removed `{siteId: 1}` parameter.

My system is not affected as my primary site (now secondary) keep the same URL structure. But of course, I guess this can be fixed otherwise.

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/comments/releases/tag/1.0.3)
