### ISSUE TITLE
Localization of JS file

### ISSUE THREAD

**Issue by rtrudel** [verbb/comments#97]
### Description
Impossible to localize/translate the "Save" button on comment edit as the button label is called by Javascript in
`verbb/comments/src/resources/comments.js` (line 474)

`form.querySelector('.cc-f-btn').innerHTML = 'Save';`

Maybe a suggestion (but it's the ugly way, you may have better!): 
Let user set it with `window.comments.saveLabel = 'Enregistrer';`
Then change: 
`form.querySelector('.cc-f-btn').innerHTML = 'Save';`
For something like
`form.querySelector('.cc-f-btn').innerHTML = window.comments.saveLabel ? window.comments.saveLabel : 'Save';`

### Additional info

- Plugin version: 1.0.2
- Craft version: 3.0.26.1

**Comment by rtrudel** [comment]
I worked around using the custom templates. I still suggest to do something about it :)

**Comment by engram-design** [comment]
Yep, good point. Note we take care of this in other instances using attributes like `data-labels` https://github.com/verbb/comments/blob/b98156734d8e5e8b06947c133d0f09fc04c35edd/src/templates/_special/comment.html#L64, looks like we've just missed this one.

**Comment by rtrudel** [comment]
Thanks for the quick reply. Does that means I can just add this attribute or it's better to wait a fix from you for this?

**Comment by engram-design** [comment]
Nah, best to wait for a proper fix!

**Comment by engram-design** [comment]
Improved in [1.0.3](https://github.com/verbb/comments/releases/tag/1.0.3)
